### ISSUE TITLE
Enable HTTP gzip compression

### ISSUE THREAD

**Issue by radojko** [moleculerjs/moleculer-web#100]
What is the best way to to enable HTTP gzip compression, this option can improve API performance over HTTP.

**Comment by icebob** [comment]
Did you try to use the https://github.com/expressjs/compression middleware?

**Comment by radojko** [comment]
I didn't know for this:

> express.compress maintains a minimum file size threshold; files with a size below this threshold (default: 1024 bytes) won't get compressed;
