### ISSUE TITLE
Is there a case in which I don't need body parsers?

### ISSUE THREAD

**Issue by Gadi-Manor** [moleculerjs/moleculer-web#106]
I spent the last couple of hours trying to figure out where did my body parameters disappeared.
Eventually, after digging into the code, I saw that what I was missing was `urlencoded: { extended: true }` (I had just the json part). 
So my question is, why do I need to set it explicitly?

**Comment by icebob** [comment]
Because in microservices I think the JSON request/response is the default and not the urlencoded POST requests.

**Comment by Gadi-Manor** [comment]
Isn't the JSON parser set by default? Then why not both?
Could it cause issues when both parsers are set?

**Comment by icebob** [comment]
It doesn't cause issues, just I thought it can be enough.
