### ISSUE TITLE
Multipart special events for file size limits

### ISSUE THREAD

**Issue by nicklasfrahm** [moleculerjs/moleculer-web#109]
I've been playing around with the multipart integration of the new `0.9.0-beta2` version. However I am not sure how to detect if the file exceeds the limits. Busboy has a special `limit` event, which is documented [here](https://www.npmjs.com/package/busboy#busboy-special-events), but I am not sure how to integrate it. Would it make sense to integrate it in some way in `moleculer-web` itself via the `ctx.meta` or similar?

If somebody has any idea, let me know and I'll be happy to submit a PR.

**Comment by icebob** [comment]
Hi,

these events are not handled in moleculer-web. Here is the relevant lines: https://github.com/moleculerjs/moleculer-web/blob/925f127c3819d4283969d8668be29f3526231b40/src/alias.js#L138-L170

My opinion is that we should create a MoleculerClientError with specific `type` and call the `sendError` built-in method like here: https://github.com/moleculerjs/moleculer-web/blob/925f127c3819d4283969d8668be29f3526231b40/src/alias.js#L151

**Comment by nicklasfrahm** [comment]
@icebob This sounds like a good approach. Let's have a look at my particular usecase then to validate it.

I am using the _multipart_ action to send a stream to a service that writes to MongoDB GridFS. How would I, if the limit is exceeded, know that I need to drop this item from my database? I thought about this a bit, but it seems like your proposal is only one part of the solution, because it only sends out an error to the client. How would I do the cleanup in such a case, where an incomplete file is regarded as corrupt and should be removed?

**Comment by icebob** [comment]
Do you have idea how we can add events?

**Comment by icebob** [comment]
@nicklasfrahm could you check that this implementation is good for you? https://github.com/moleculerjs/moleculer-web/commit/6a755e1ba43c0a4188edc835f20b328eb2f50f5b

```js
routes: [
    {
        // Route level busboy config.
        busboyConfig: {
            limits: {
                files: 1
            }
            // Can be defined limit event handlers
            onFilesLimit(busboy, alias, service) {
                // this.broker.emit("file-limit.exceeded");
            }
        },
    }
]
```
