### ISSUE TITLE
Body Validation

### ISSUE THREAD

**Issue by olivinesguerra** [moleculerjs/moleculer-web#111]
Hello Mr. Developer :D

This is my code on my login 👍 

		login: {
			body:{
				email: "string",
				password: "string"
			},
			handler(ctx) {
				console.log(ctx.params.body);
				return `Welcome, ${ctx.params.email}`
			}
		}

![Screen Shot 2019-03-29 at 10 29 55 AM](https://user-images.githubusercontent.com/5746116/55205389-a2269200-520d-11e9-8954-79026e71711d.png)
Question:

The params is the only to validate the parameters but only for query. Is there anyway I could validate body parameters?

body-parser : enabled
mergeParams: false

I can see through the logs.

Thank

**Comment by icebob** [comment]
You should use `params` name for validation. E.g.:
```js
login: {
	params: {
		body: { type: "object", props: {
			email: "string",
			password: "string"
		}}
	},
	handler(ctx) {
		console.log(ctx.params.body);
		return `Welcome, ${ctx.params.email}`
	}
}
```

**Comment by olivinesguerra** [comment]
thank you
