### ISSUE TITLE
BUG  incorrect parse "user/users" routes in API-GATEWAY

### ISSUE THREAD

**Issue by Remigar2012** [moleculerjs/moleculer-web#114]
API GATEWAY
incorrect parse "user/users" routes in API-GATEWAY

### 1) users.service.js
```
module.exports = {
	name: "users",

	settings: {
	},

	dependencies: [],

	actions: {
	  create: {
	    params: {
	      name: "string",
	      email: "email",
	      password: "string"
	     },
           handler (ctx) {
	     return this.createUser(ctx.params);
	   }
	},
	events: {},
	methods: {
            ...
         },
        created () {

	},
        started () {

	},
        stopped () {

	},
...
```
### 2) api.service.js
```
module.exports = {
	name: "api",
	mixins: [ApiGateway],
	// dependencies: ["auth"],
	// More info about settings: https://moleculer.services/docs/0.13/moleculer-web.html

	settings: {
		port: process.env.PORT || 3000,
		path: "/api",
		routes: [
			{
				path: "",
				mappingPolicy: "restrict",
				aliases: {
					"POST users": "users.create",
				},
				bodyParsers: {
					json: true,
				},
			},
			{
				path: "/user",
				mappingPolicy: "restrict",
				aliases: {
					"POST users": "users.create",
				},
				bodyParsers: {
					json: true,
				}
			},

			{
				path: "/auth",
				mappingPolicy: "restrict",
				aliases: {
					"POST users": "users.create",
				},
				bodyParsers: {
					json: true,
				}
			},

		],
	},
	methods: {
        }
};
```

### 3) moleculer.config.js
```
 */
module.exports = {

	namespace: "",
	nodeID: null,
}
```

### 4) package.json
```
...
"devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint": "^5.10.0",
    "jest": "^23.6.0",
    "jest-cli": "^23.6.0",
    "moleculer-repl": "^0.5.3"
  },
  "dependencies": {
    "dotenv": "^7.0.0",
    "ioredis": "^4.2.0",
    "jsonwebtoken": "^8.5.1",
    "moleculer": "^0.13.8",
    "moleculer-web": "^0.8.5",
    "moment": "^2.24.0",
    "rethinkdb": "^2.3.3",
    "url": "^0.11.0"
  },
...
```

#### PRE INFO
<img width="341" alt="routesregister" src="https://user-images.githubusercontent.com/38878586/56357408-58b1dd00-61e4-11e9-9f30-cbd9f9d5fc7b.png">

0) ARRAY ROUTES - length 3 
1)  routes[0] PATH - with prefix
2)  routes[1] PATH - with prefix
3)  routes[2] PATH - no prefix or (if mappingPolicy:"all") prefix "/" 
##### 1 route request and response
<img width="1647" alt="1 route" src="https://user-images.githubusercontent.com/38878586/56356774-71b98e80-61e2-11e9-8365-601a140daeef.png">
RESULT 1 route ---> WORKING

#### 2 route request and response
<img width="1610" alt="2 route" src="https://user-images.githubusercontent.com/38878586/56357242-d9240e00-61e3-11e9-8917-40e789e1344c.png">
RESULT 2 route ---> WORKING

#### 3 route request and response
<img width="1572" alt="3 route" src="https://user-images.githubusercontent.com/38878586/56357261-ea6d1a80-61e3-11e9-8e01-a3865054e2bb.png">
RESULT 3route ---> ERROR  
Prefix route "/s" and 404 
if aliases === { "POST user(not userS):"users.create"}
then Prefix route in console ===  "/" and 404

#### PRE INFO
3 route switch with 2 route 
#### new 2(old 3 route) request and response
<img width="1384" alt="2 case" src="https://user-images.githubusercontent.com/38878586/56357752-484e3200-61e5-11e9-8792-d52051c81580.png">
RESULT new 2(old 3 route) ---> ERROR  and === ERROR 1 CASE 3 route

#### PRE INFO
do the third route first

#### request and response
<img width="1481" alt="3 case" src="https://user-images.githubusercontent.com/38878586/56358039-18ebf500-61e6-11e9-9fb1-2dfbcc917051.png">
RESULT WORKING and OTHER ROUTES NOT WORKING

# how it works?

PS this bug only users/user aliases

**Comment by icebob** [comment]
Thanks, I will investigate it...

**Comment by intech** [comment]
@icebob problem in here
![Снимок экрана от 2019-04-19 01-01-57](https://user-images.githubusercontent.com/451306/56391142-d60a3b80-623e-11e9-9ab2-200aef4e1a21.png)
https://github.com/moleculerjs/moleculer-web/blob/master/src/index.js#L162

**Comment by icebob** [comment]
Thanks @intech, yes, but I don't know, how I can fix it.

**Comment by intech** [comment]
@icebob 
add sorting routes and add slashes for full check segment url
```js
this.routes.sort((a, b) => addSlashes(b.path).split("/").length - addSlashes(a.path).split("/").length);
...
url+"/".startsWith(route.path+"/")
```
fixed this problem path and aliases priority check and add many probles with test response 404 error (path not found - service and action not found - aliases).

**Comment by intech** [comment]
```js
describe("Test route.path and aliases", () => {
	let broker;
	let app;
	let service;
	let nextHandler = jest.fn((req, res) => res.sendStatus(200));

	beforeAll(() => {

		broker = new ServiceBroker({ logger: false });

		service = broker.createService(ApiGateway, {
			settings: {
				path: "/api",
				routes: [{
					path: "/te",
					aliases: {
						"GET test"(req, res) {
							res.end("/api/te/test");
						}
					}
				},{
					path: "",
					aliases: {
						"GET test"(req, res) {
							res.end("/api/test");
						}
					}
				}]
			}
		});

		return broker.start();
	});

	afterAll(() => {
		return broker.stop();
	});

	it("GET /api/te/test", () => {
		return request(service.server)
			.get("/api/te/test")
			.then(res => {
				console.log(res.body);
				expect(res.statusCode).toBe(200);
				expect(res.text).toBe("/api/te/test");
				expect(nextHandler).toHaveBeenCalledTimes(0);
			});
	});

	it("GET /api/test", () => {
		return request(service.server)
			.get("/api/test")
			.then(res => {
				console.log(res.body);
				expect(res.statusCode).toBe(200);
				expect(res.text).toBe("/api/test");
				expect(nextHandler).toHaveBeenCalledTimes(0);
			});
	});
});
```

**Comment by intech** [comment]
@icebob temporary fix, please refactory this code:
```js
this.routes.sort((a, b) => addSlashes(b.path).split("/").length - addSlashes(a.path).split("/").length);

console.log(this.routes.map(p => p.path));

const filter = this.routes.filter(r => r.path.split("/").length <= url.split("/").length);

for (const route of filter) {

    // url: /api/test

    // path: /api/te   alias: test
    // path: /api      alias: test/123

    let path = route.path;
    // Trim trailing slash
    if (path.length > 1 && path.endsWith("/"))
        path = path.slice(0, -1);

    for (let i = path.split("/").length; i > 0; i--) {
        url = url.split("/").slice(0, i).join("/") || "/";
        if ((path.endsWith("/") && route.aliases && route.aliases.length > 0) || path === url) {
            // Update URLs for middlewares
            req.baseUrl = route.path;
            req.url = req.originalUrl.substring(route.path.length);
            if (req.url.length === 0 || req.url[0] !== "/")
                req.url = "/" + req.url;
            return this.routeHandler(ctx, route, req, res);
        }
    }
}
```

**Comment by intech** [comment]
@icebob do you need help?

**Comment by icebob** [comment]
@intech thanks, but I'm thinking about a different solution in v0.9. I want to add a new alias store which is independent of the route. it can solve this issue and other ones (like using params in route path)

**Comment by intech** [comment]
@icebob сan I somehow help with the implementation? You can write me a detailed task.

**Comment by Remigar2012** [comment]
@icebob nice)

**Comment by icebob** [comment]
@intech yes, it would be great.

So my idea is that 
1. we should create a `this.aliases = []` store inside the service here: https://github.com/moleculerjs/moleculer-web/blob/6bc5668d827433a96f33965c613bf730ff5e1b81/src/index.js#L113 
(instead of route-based alias store). 

2. We will fill it in `createRouteAliases` & `regenerateAutoAliases` function. Instead of `route.aliases.push(...)`, use `this.aliases.push...` and concatenate route.path & alias path. Of course, we should solve to clear old aliases when the functions called again _(reload route when a new service started or stopped)_. It's not hard because there is a pointer to the `route` in Alias instances.

3. In `rest` action before we iterate `routes`, we check the `this.aliases` and find which alias matches the request url. If we find, we will call the `aliasHandler`. 

4. If not found _(because we use the whitelist instead of aliases)_, we use the original method, find the `route` by path (if `mappingPolicy != "restrict"`) but skip the aliases part here because we processed it earlier, so we should call only this part: https://github.com/moleculerjs/moleculer-web/blob/6bc5668d827433a96f33965c613bf730ff5e1b81/src/index.js#L344-L349

So in the case of  @Remigar2012 example, we have the following global aliases:
```
POST /api/users => users.create
POST /api/user/users => users.create
POST /api/auth/users => users.create
```
The alias handler uses regexp to find the matched alias, it will find the correct path.
By the way, with this solution we can use routes like this one:
```js
routes: [
    {
        path: "/api/:company",
        aliases: {
            "GET /users": "company.users",
            "GET /offices": "company.offices",
        }
    }
]
```

**Comment by icebob** [comment]
@intech are you working on it?

**Comment by intech** [comment]
@icebob no, please excuse me, business has changed my plans. In May, there may be no free time :(

**Comment by icebob** [comment]
No problem. In this case, I will do it.

**Comment by icebob** [comment]
I've implemented it. It was a bit more difficult than I thought, but it's done & [tested](https://github.com/moleculerjs/moleculer-web/blob/937c3323a8ab7cf1e32abec7b08448edd833ffdc/test/integration/index.spec.js#L3820).
