### ISSUE TITLE
Improve documentation for handler-only aliases

### ISSUE THREAD

**Issue by andersnm** [moleculerjs/moleculer-web#115]
Hi,

I'm in the process of implementing some moleculer-web HTTP endpoints that only call alias handler functions, and should not invoke any actions. The following service implements 3 endpoints wrongly based on guessing and the documentation (hello/world, universe, upload), and the last one is what seems to work the best (hello/anders).

IMO the docs could benefit from some improvements here. (but also other things, e.g support for async alias handlers, don't rely on promise resolve order and ignoring exceptions)

```js
const { ServiceBroker } = require("moleculer");
const ApiService = require("moleculer-web");
const sleep = (ms) => new Promise(res => setTimeout(res, ms));
const broker = new ServiceBroker({ logger: console });

const webService = {
    name: 'molewebtest',
    version: 'v1',
    mixins: [ApiService],
    settings: {
        port: 4000,
        routes: [
            {
                path: '/hello',
                aliases: {
                    '* world': helloWorld,
                    '* universe': helloUniverse,
                    "* upload"(req, res) {
                        parseUploadedFile(req, res);
                    },
                    '* anders': helloAnders,
                },
            },
        ],
    }
};

function helloWorld(req, res, callback) {
    // Naive handler generates error:
    // MoleculerServerError: No alias handler
    res.end("world");
    callback();
}

async function helloUniverse(req, res, callback) {
    // This is wrong on many levels, but does not return an error. Async alias handlers are not supported. 
    // This invokes the callback too late, and gets stuck forever in the aliasHandler promise
    await sleep(100);
    res.status = 200;
    res.end("universe");
    callback();
    return Promise.resolve();
}

function parseUploadedFile(req, res) {
    // Guesswork based on the the documentation at https://moleculer.services/docs/0.13/moleculer-web.html
    // No error, because it ignores the callback and gets stuck forever in the aliasHandler promise
    res.end("upload");
}

function helloAnders(req, res, callback) {
    // This looks to be the "correct" way of doing it:
    // No visible error. Although "No alias handler" is still thrown behind the scenes, but the exception is ignored because the
    // aliasHandler promise is resolved before the catch handler via `res.once("finish", () => resolve(true));` in routeHandler()
    res.end("anders", callback);
}

broker.createService(webService);
broker.start();
```

**Comment by icebob** [comment]
The third parameter is not a callback, it's the `next` which call the next middleware. You should use it only if your code is a middleware and not an alias handler. If you return response in your handlers with res.end, don't call the callback/next function.

_Promise response is not handled in alias handlers, because it is Express middleware compatible._

**Comment by andersnm** [comment]
Hi,

Hm, guess you are right. I got confused by reading the moleculer-web source code. Its far from obvious what's going on there with mixed callbacks, promises, middleware chains, and sudden resolve via res.once("finish"...). Thus the request for improved documentation, since this use case isn't covered entirely and apparently requires extensive knowledge about the internals of moleculer-web to get right.

Key takeaway is res.end() (magically) short circuits the internal promise chain in moleculer-web, which bypasses invoking any actions.

**Comment by icebob** [comment]
@AndreMaz Could you help with this to add some notes to the docs about it?

**Comment by AndreMaz** [comment]
I've added a note with a function signature and an example. Hope it helps
