### ISSUE TITLE
Can I make an action private?

### ISSUE THREAD

**Issue by polomoshnov** [moleculerjs/moleculer-web#116]
Say, I have a service called API and it's exposed via `moleculer-web` so that a UI running in a web browser can access it. The matter is that I want to restrict some of the actions the API has so that the UI cannot call them but, internally, I still can `broker.call` them from within any other service.

**Comment by icebob** [comment]
Please check action visibility: https://moleculer.services/docs/0.13/actions.html#Action-visibility

**Comment by polomoshnov** [comment]
Thanks! That answers my question. Great work, by the way!
