### ISSUE TITLE
How to get headers and set cookies from within an action?

### ISSUE THREAD

**Issue by polomoshnov** [moleculerjs/moleculer-web#117]
In a `signIn` action I'm implementing along with `signUp` and `signOut` I need to get the IP address of the client and its `user-agent` string and store this info in a database so that it can later be used to help identify the origin of the client. Upon signing in I'm also issuing a new token for the client to be used in all subsequent requests; and this token needs to be set by the backend as an HTTP cookie in the response. Could anybody suggest how I can do that? 

I've seen that I can set headers via `ctx.meta.$responseHeaders` but is there something like `ctx.meta.$requestHeaders`? And also, should I use `ctx.meta.$responseHeaders` to set cookies? Please suggest what would be the best way to get/set headers/cookies in my use case. Thanks a lot for any help!

**Comment by icebob** [comment]
You can use `ctx.meta.$responseHeaders` to set cookie in the response. For `ctx.meta.$requestHeaders`, use `onBeforeCall` and set headers what you need into the Context meta.
Similar answers: 
- https://github.com/moleculerjs/moleculer-web/issues/93#issuecomment-446039185
- https://github.com/moleculerjs/moleculer-web/issues/82#issuecomment-437668275
https://github.com/moleculerjs/moleculer-web/issues/49#issuecomment-393157380

**Comment by polomoshnov** [comment]
Ok, thank you very much! Now I understand.

**Comment by HighSoftWare96** [comment]
@icebob Is there any way to access the HTTP request from the ctx of the action? I'm asking this because I want to access the request headers without modifying the moleculer node that holds the gateway...

**Comment by icebob** [comment]
Then you should put all headers into the `ctx.meta`. You can't send the whole `req` because it's not serializable.
