### ISSUE TITLE
I would like to take a XML request, What is the best way to do this?

### ISSUE THREAD

**Issue by jianzi0307** [moleculerjs/moleculer-web#120]
In my scenario, one of my API's needs to accept a XML post body, rather than a JSON one.

I have an API where I want to do a POST request, but my POST request needs to be send of as XML. So this is what my API looks like:

`POST /api/store?sign=xxx-xxx-xxx-xxx&time=123456`

the post request body:

```xml
<?xml version="1.0"?>
<methodCall>
   <methodName>myMethod</methodName>
    <params>
      <param>
         <value><string>hello</string></value>
      </param>
   </params>
</methodCall>
```

However, my body comes back empty. Any idea how I can fix this? Ideally, I would like to take this XML request. What is the best way to do this?

**Comment by jianzi0307** [comment]
```javascript
'use strict';

const bodyParser = require('body-parser');
require('body-parser-xml')(bodyParser);

export default {
  path: '/api',
  mappingPolicy: 'restrict',
  mergeParams: false,
  use: [bodyParser.xml()],
  aliases: {
    'store'(req, res) {
      console.log(req.body);
      res.end('success');
    }
  }
};
```

**Comment by har17bar** [comment]
@jianzi0307 thank you ))
