### ISSUE TITLE
http server default timeout override option

### ISSUE THREAD

**Issue by akshaykarode** [moleculerjs/moleculer-web#121]
Nodejs http servers default timeout (2 min) should be override by configuration.

**Comment by akshaykarode** [comment]
Hello @icebob ,
The past few weeks i was struggling to increase servers requests default timeout, then i found moleculer-web use http module underneath to create server.
So thought to provide configurable option in settings , that user can manipulate as per need of server settings.
My team currently using Moleculer Framework for Server API's. So, need to have this feature as early as possible. I would like to contribute the solution and push into the repository.
Please let me know what can be done to have this on live.
`        settings :{
                  httpServerTimeout:180000, // 5 minutes
           }
`

LifeCycle change:
            
          created() {
		     if (this.settings.server !== false) {

			if (_.isObject(this.settings.server)) {
				// Use an existing server instance
				this.server = this.settings.server;
			} else {
				// Create a new HTTP/HTTPS/HTTP2 server instance
				this.createServer();
			}

			// set http server timeout
			if(this.settings.httpServerTimeout){
				this.logger.info("Override Default http/https Server Timeout", this.settings.httpServerTimeout);
				this.server.setTimeout(this.settings.httpServerTimeout)
			}

			/* istanbul ignore next */
			this.server.on("error", err => {
				this.logger.error("Server error", err);
			});

			this.logger.info("API Gateway server created.");
		}

**Comment by icebob** [comment]
Good solution please create a PR and send it to then `next` branch.

**Comment by akshaykarode** [comment]
I am not able to push the code due to access denied.
`remote: Permission to moleculerjs/moleculer-web.git denied to akshaykarode.`

**Comment by icebob** [comment]
First of all, you should fork the repo, guide: https://www.youtube.com/watch?v=rgbCcBNZcdQ
