### ISSUE TITLE
res.send is not a function

### ISSUE THREAD

**Issue by elixiao** [moleculerjs/moleculer-web#133]
I read the [docs](https://moleculer.services/docs/0.13/moleculer-web.html) and write the following code copied from docs.

```js
const ApiGateway = require('moleculer-web')

module.exports = {
  name: 'api',
  mixins: [ApiGateway],
  settings: {
    port: process.env.PORT || 3000,
    routes: [
      {
        path: '/api',
        mergeParams: false,
        mappingPolicy: 'restrict',
        aliases: {
          'POST upload'(req, res) {
            this.parseUploadedFile(req, res)
          },
          'GET custom'(req, res) {
            res.send('hello from custom handler')
          }
        }
      }
    ],
    assets: {
      folder: 'public'
    }
  },
  actions:{
    parseUploadedFile() {
      console.log('parseUploadedFile')
    }
  }
}
```

I use Postman to test the api  `GET http://localhost:3000/api/custom` and `POST http://localhost:3000/api/upload?name=1`, I got the following erros:

```json
{
  "name": "TypeError",
  "message": "res.send is not a function",
  "code": 500
}
```

```json
{
  "name": "TypeError",
  "message": "this.parseUploadedFile is not a function",
  "code": 500
}
```

Why? Is my code wrong?

**Comment by elixiao** [comment]
@icebob I update the dependency but the error still exists. Here is my package.json: 

```json
{
  "name": "alarm",
  "version": "1.0.0",
  "description": "My Moleculer microservices project",
  "scripts": {
    "dev": "moleculer-runner --repl --hot services",
    "start": "moleculer-runner",
    "cli": "moleculer connect NATS"
  },
  "keywords": [
    "microservices",
    "moleculer"
  ],
  "author": "",
  "devDependencies": {
    "moleculer-repl": "^0.5.3"
  },
  "dependencies": {
    "moleculer": "^0.13.0",
    "moleculer-http-client": "^0.1.1",
    "moleculer-web": "^0.9.0-beta5",
    "nats": "^1.0.1"
  },
  "engines": {
    "node": ">= 8.x.x"
  }
}
```

**Comment by icebob** [comment]
1. The `res.send` is an ExpressJS command but moleculer-web is not Express-based. It uses native Node.js HTTP server, so you should send the response with `res.write` & `res.end`.
2. The `this.parseUploadedFile` line calls a method and not an action. So you should define this as a method.

**Comment by elixiao** [comment]
Thanks. The code works now when I change `send` to `end`, and `actions` to `methods`. Will moleculer-web integrate with express or koa later? Native HTTP server api is really obscure for beginners.

**Comment by icebob** [comment]
No, because with Express or Koa no need any specific code, just call the action with `broker.call` and send back the response in your routes, like: 
```
app.get("/users", async (req, res) => res.json(await broker.call("users.list")));
```

**Comment by elixiao** [comment]
OK, got it. Thanks again for your time and help. I will close this issue.
