### ISSUE TITLE
BUG routes with identical path aborted at first match

### ISSUE THREAD

**Issue by muenalan** [moleculerjs/moleculer-web#135]
I do generate routes through a script, and would like to simply list them as the come. Note: I do need to have fine grained control which aliases require authentication (the source is an openapi spec). 

BUG: The first route *path* match makes any further aliases not match, although their path would also match. Even worse, the alias finding switches to service name resolution, which is very unexpected.

```
routes : [
  { path: '/v2',
    authentication: true,
    aliases: 
     { 'delete 0.0.2/lims/group/:id': [Function: delete 0.0.2/lims/group/:id] } },
  { path: '/v2',
    authentication: false,
    aliases: 
     { 'get 0.0.2/lims/group/findByStatus': [Function: get 0.0.2/lims/group/findByStatus] } },
]
```

I could trace the problem in 0.8.5 to

```
156: if (url.startsWith(route.path)) {
.....: 
163:  return this.routeHandler(ctx, route, req, res);

 }

```
which seems a rather odd behaviour. I thought about a better design, but the route-resolution seems rather bony, and i wonder if an iteration of all routes until an alias matches would be a much better solution ?

**Comment by AndreMaz** [comment]
Can you try v.0.9 beta and see if it works properly ?

**Comment by muenalan** [comment]
Positive+Great ! Although v.0.9 seems to have breaking changes (sendResponse() makes trouble) , I'll try to migrate; its worth it.

**Comment by muenalan** [comment]
Positive+Great ! Although v.0.9 seems to have breaking changes (sendResponse() makes trouble) , I'll try to migrate; its worth it. Should be moved to known-bugs in v0.8.5, i suppose.

**Comment by AndreMaz** [comment]
Awesome. You can check the changelog here https://github.com/moleculerjs/moleculer-web/blob/master/CHANGELOG.md
