### ISSUE TITLE
suggestion - chalk config

### ISSUE THREAD

**Issue by dkuida** [moleculerjs/moleculer-web#138]
Hello

chalk is used inside the middleware.

The issue is - that an external logger is hooked to ServiceBroker, logged messages about error status results come with color encoded as if it is a part of a message. So it needs to be cleaned up externally - which is quite redundant.
It can be disabled with 
```javascript
chalk.supportsColor.level = 0
```

but

1. it is global
2. it is version dependant 

my proposal is to have as part of the settings to either

1. send chalk config ( do not really like it - class should not expose implementation detail)
2. expose enable/disable property for colors.

What do you think?

I could create PR for that after the decision

**Comment by icebob** [comment]
Hi,

the second option would be better. Please make a PR. By the way, in the core Moleculer package we killed the chalk lib and using [kleur](https://github.com/lukeed/kleur) to reduce dependencies. Could you make this change in this PR, as well?

**Comment by icebob** [comment]
@dkuida Any updates?
