### ISSUE TITLE
Service '__webpack_hmr.client' is not registered

### ISSUE THREAD

**Issue by aronanda** [moleculerjs/moleculer-web#139]
I keep getting this 404 error when I run the Web API service. Even if I don't have webpack in the project. Any ideas?

**Comment by icebob** [comment]
Webpack is a frontend module. Somebody called your API from a webpack frontend app with enabled hot-reload feature.

**Comment by aronanda** [comment]
I figured it was something like that. I must have a rogue webpacker somewhere.
