### ISSUE TITLE
bodyParsers settings for FormData

### ISSUE THREAD

**Issue by rishighan** [moleculerjs/moleculer-web#140]
I am trying to `POST` `FormData` from a React frontend using `axios` The client-side constructs the `FormData` object as it should, and I am able to iterate through the entries and see that my `File` is appended to `FormData`

Relevant code:
```javascript
const drop = (file) => {
    const fd = new formData();
    fd.append('fileData', file);
    axios.post('http://localhost:3030/api/upload', fd, {
        headers: {
            'Content-Type': `multipart/form-data; boundary=${fd._boundary}`,
        }
    })
    .then(response => {
        console.log(response);
    })
    .catch(error => {
        console.log(error);
    });
}
```

This is my API:
```javascript
"use strict";
const Busboy = require('busboy');
const ApiGateway = require("moleculer-web");
function uploader(req, res, next) {
	console.log(req.headers)
	const busboy = new Busboy({headers: req.headers});
	busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
		console.log('File [' + fieldname + ']: filename: ' + filename + ', encoding: ' + encoding + ', mimetype: ' + mimetype);
		file.on('data', function(data) {
		  console.log('File [' + fieldname + '] got ' + data.length + ' bytes');
		});
		file.on('end', function() {
		  console.log('File [' + fieldname + '] Finished');
		});
	  });
	  
	res.end(next);
}

module.exports = {
	name: "api",
	mixins: [ApiGateway],
	// More info about settings: https://moleculer.services/docs/0.13/moleculer-web.html
	settings: {
		port: process.env.PORT || 3030,
		bodyParsers: {
			json: false,
			urlencoded: false,
		},
		routes: [{
			path: "/api",
			aliases: {
				"POST /upload": uploader,
			},
		}],
	}
};
```
The request reaches the API, but`req.body` is always empty.
I banged my head around this problem and see nothing wrong with how I am constructing `FormData` The only place left for me to investigate is the API's `bodyParsers` setting.

I understand that for `multipart/form-data` requests, normal `json` and `urlencoded` parsers won't work and hence why I disabled them in favor of `busboy` But even that is not working.

Have I discovered a bug? Or is there a place in the documentation which could shed some light on this particular problem?

**Comment by intech** [comment]
@rishighan FormData fields is available in ctx.meta.$multipart

**Comment by rishighan** [comment]
Hmm. I tried that as well. 

This is my service:

```javascript
"use strict";



module.exports = {
	name: "assets",
	version: 1,
	settings: {

	},
	dependencies: [],
	actions: {
		upload: {
			cache: {
				keys: [],
			},
			params: {
				// payload: { type: "object", optional: false } ,

			},
			handler(context) {
                           console.log(context.params); // <- empty
                           console.log(context.meta) // <- undefined
				

			}
		}
	},
	events: {

	},
	methods: {

	},

	/**
	 * Service created lifecycle event handler
	 */
	created() {
		
		console.log("Assets service instance created");
	},

	/**
	 * Service started lifecycle event handler
	 */
	started() {
	},

	/**
	 * Service stopped lifecycle event handler
	 */
	stopped() {

	}
};
```

**Comment by rishighan** [comment]
I am testing this on ‘localhost’ in Firefox with CORS restrictions disabled. I tried updating to the beta tag of ‘moleculer-web’ and trying ‘ctx.meta.$multipart’ but still getting nothing...

**Comment by icebob** [comment]
https://github.com/moleculerjs/moleculer-web/blob/master/CHANGELOG.md#file-upload-aliases

```
"POST /": "multipart:assets.upload",
```

**Comment by rishighan** [comment]
I took that example and tried to hit `http://localhost/3000/upload`, keep getting `503 Unavailable`

**Comment by rishighan** [comment]
> https://github.com/moleculerjs/moleculer-web/blob/master/CHANGELOG.md#file-upload-aliases
> 
> ```
> "POST /": "multipart:assets.upload",
> ```

Are my aliases incorrectly configured? I am on the most current beta for `moleculer-web` and using the file upload aliases and my action does have the `multipart:` tag. Still getting an empty `ctx.params`

**Comment by rishighan** [comment]
Separately, for my own sanity, I took the code in the link you had shared, and changed it to point the actions in my service.

I tried hitting `http://localhost:4000/upload` and keep getting a `503 Service Unavailable` and I am not sure if I understand the route configuration correctly.

I have a service called `assets.service.js` which I detailed in this [comment](https://github.com/moleculerjs/moleculer-web/issues/140#issuecomment-532931831)

```javascript
"use strict";
const Busboy = require("busboy");
const ApiGateway = require("moleculer-web");

module.exports = {
	mixins: [ApiGateway],
	settings: {
		port: 4000,
		path: "/upload",
		routes: [
			{
				path: "",
				// You should disable body parsers
				bodyParsers: {
					json: false,
					urlencoded: false
				},
				mappingPolicy: "restrict",
				aliases: {
					// File upload from HTML multipart form
					"POST /": "multipart:assets.upload",
                    
					// File upload from AJAX or cURL
					"PUT /": "stream:assets.upload",

					// File upload from HTML form and overwrite busboy config
					"POST /multi": {
						type: "multipart",
						// Action level busboy config
						busboyConfig: {
							limits: {
								files: 3
							}
						},
						action: "assets.upload"
					}
				},

				// Route level busboy config.
				// More info: https://github.com/mscdex/busboy#busboy-methods
				busboyConfig: {
					limits: {
						files: 1
					}
					// Can be defined limit event handlers
					// `onPartsLimit`, `onFilesLimit` or `onFieldsLimit`
				},

			}
		]
	}
};
```

**Comment by icebob** [comment]
Could you create a reproduce repo?

**Comment by rishighan** [comment]
Sure: https://github.com/rishighan/assets-service

**Comment by icebob** [comment]
And how do you send file?

**Comment by icebob** [comment]
The problem is that, you set the version number in `assets` service, so your action name in aliases is `v1.assets.upload` and not `assets.upload`

**Comment by rishighan** [comment]
@icebob that was it! I did not know that an action would've to be accessed with a version prefix, if the service has that property defined. 
One more thing to note: the `FileStream` object is made available in `ctx.params` and not `ctx.meta.$multipart` as previously mentioned.

Either way, thanks for your help, I can finally close this issue.

**Comment by icebob** [comment]
You're welcome.

I think nobody mentioned that File stream will be in `ctx.meta`. The `ctx.params` will be the `Stream` and the additional `FormData` will be in `ctx.meta.$multipart`.

**Comment by huynt0** [comment]
> You're welcome.
> 
> I think nobody mentioned that File stream will be in `ctx.meta`. The `ctx.params` will be the `Stream` and the additional `FormData` will be in `ctx.meta.$multipart`.

How to get it From Route-level middlewares ?  I'm testing with req.body but it's empty
