### ISSUE TITLE
Multiple Assets path & Hosting SPA

### ISSUE THREAD

**Issue by babnik63** [moleculerjs/moleculer-web#141]
1- Moleculer is a great project. If we can host single pages such as vuejs .vue files it will be a very useful feature. Creating multiple routes that each can host a separate single page app.

2-Also we may need to host multiple assets paths, with different permissions. now the assets just accepts one path. If it supports multiple paths will be more useful.

**Comment by icebob** [comment]
you can serve multiple assets if you use the `serve-static` middleware in your routes.

**Comment by icebob** [comment]
Here is an example: https://codesandbox.io/s/moleculer-api-routing-gi1bv?fontsize=14

_The image comes from the static2 folder._

**Comment by babnik63** [comment]
You may need to have multiple routes with referent permissions. ;-)

**Comment by babnik63** [comment]
How can we host a single page vuejs app with molecular?

**Comment by icebob** [comment]
Check this repo: https://github.com/icebob/kantab
