### ISSUE TITLE
authentication & authorization do not work 

### ISSUE THREAD

**Issue by juanmcristobal** [moleculerjs/moleculer-web#144]
Hi, i am folllow the documentation from moleculer-web, this is my api service

```
"use strict";
const ApiGateway = require("moleculer-web");

module.exports = {
	name: "api",
	mixins: [ApiGateway],

	// More info about settings: https://moleculer.services/docs/0.13/moleculer-web.html
	settings: {
		port: process.env.PORT || 8080,

		// Global CORS settings for all routes
		cors: {
			// Configures the Access-Control-Allow-Origin CORS header.
			origin: "*",
			// Configures the Access-Control-Allow-Methods CORS header.
			methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"],
			// Configures the Access-Control-Allow-Headers CORS header.
			allowedHeaders: ["*"],
			// Configures the Access-Control-Expose-Headers CORS header.
			exposedHeaders: [],
			// Configures the Access-Control-Allow-Credentials CORS header.
			credentials: false,
			// Configures the Access-Control-Max-Age CORS header.
			maxAge: 3600
		},

		routes: [
			{
				path: "/api",
				authorization: true,
				authentication: true,
				whitelist: ["**"]
			},
			{
				path: "/auth",
				// Action aliases
				authorization: false,
				authentication: false,
				aliases: {
					"POST google": "identity.google",
					"POST validatejwt": "identity.validateJWT"
				},
				bodyParsers: { json: true, urlencoded: false }
			}
		],

		methods: {
			authorize(ctx, route, req, res) {
				console.log("authorize");
				ctx.meta.user = { id: 1, name: "John Doe" };
				return Promise.resolve(ctx);
			},
			authenticate(ctx, route, req, res) {
				console.log("authenticate");
				ctx.meta.user = { id: 1, name: "John Doe" };
				return Promise.resolve(ctx);
			}
		},
		// Serve assets from "public" folder
		assets: {
			folder: "public"
		}
	}
};

```

when i call to for example 
http://localhost:8080/api/users/list

return all user but there's no trace of the messages, it doesn't go through those elements.
i am using 0.8.5 versión of moleculer-web

thanks in advance

**Comment by juanmcristobal** [comment]
My fault, methods outside from setings

**Comment by moulali1947** [comment]
Hi, 
After keeping the methods outside of settings. is it working?
Are the authentication and authorization methods when they are set to true for the following aliases?
aliases: {
					"POST google": "identity.google",
					"POST validatejwt": "identity.validateJWT"
				},

**Comment by AndreMaz** [comment]
No, `authentication` and `authorization` are hooks that you can use to do anything (e.g., validate `jtw`). These hooks are called before calling an actual handler that is declared in  `routes`.

More info here: 
- https://moleculer.services/docs/0.13/moleculer-web.html#Authorization
- https://moleculer.services/docs/0.13/moleculer-web.html#Authentication

**Comment by juanmcristobal** [comment]
> Hi,
> After keeping the methods outside of settings. is it working?
> Are the authentication and authorization methods called when they are set to true for the following aliases?
> aliases: {
> "POST google": "identity.google",
> "POST validatejwt": "identity.validateJWT"
> },

hi, i was wrong in my code, the correct code is this:
settings:{....},
methods: {
			authorize(ctx, route, req, res) {
				console.log("authorize");
				ctx.meta.user = { id: 1, name: "John Doe" };
				return Promise.resolve(ctx);
			},
			authenticate(ctx, route, req, res) {
				console.log("authenticate");
				ctx.meta.user = { id: 1, name: "John Doe" };
				return Promise.resolve(ctx);
			}
		},
