### ISSUE TITLE
How to add winston logger to moleculer-web service ?

### ISSUE THREAD

**Issue by stanislav-web** [moleculerjs/moleculer-web#149]
Hi, there!
I need to implement winston logger for my web service but i dont have created any **ServiceBroker** . My services started directly from console launcher... 

`/node_modules/.bin/moleculer-runner --repl --hot --envfile .env.dev endpoints`

> endpoints - is directory where my services are located in and exports by default Nodejs module.exports = {}

So , my question is actual because i don't know how to implement winston logger instead of basic console. Can anyone help me ?

**Comment by icebob** [comment]
You should create a `moleculer.config.js` and put the logger config into it:
https://moleculer.services/docs/0.13/logging.html#Winston

```js
// moleculer.config.js

const winston = require("winston");
const { extend } = require("moleculer").Logger;

module.exports = {
    logger: bindings => extend(winston.createLogger({
        format: winston.format.combine(
            winston.format.label({ label: bindings }),
            winston.format.timestamp(),
            winston.format.json(),
        ),
        transports: [
            new winston.transports.Console()
        ]
    }))
};
```
```

**Comment by stanislav-web** [comment]
@icebob its doesn't work 
I added winston.transports.File  but logs files does not created. 
`transports: [
      new winston.transports.Console(),
      new winston.transports.File({ filename: './error.log', level: 'debug' }),
      new winston.transports.File({ filename: './combined.log' })
    ]`

![Снимок экрана 2019-10-29 в 15 17 29](https://user-images.githubusercontent.com/5216760/67770689-8a431500-fa5f-11e9-9566-48973e4d838a.png)
![Снимок экрана 2019-10-29 в 15 19 53](https://user-images.githubusercontent.com/5216760/67770714-97f89a80-fa5f-11e9-8dbc-662aafeba94a.png)

As you can see console working properly as before with default logger configuration
`LOG_LEVEL=info
LOG_FORMATTER=default`

**Comment by icebob** [comment]
Please try it again with Moleculer 0.14 and Moleculer-web 0.9

**Comment by zerotn3** [comment]
> Please try it again with Moleculer 0.14 and Moleculer-web 0.9

How to use with new version bro ?.thank

**Comment by zerotn3** [comment]
> Please try it again with Moleculer 0.14 and Moleculer-web 0.9

Im upgrade to latest version.
`type: "Winston",
			options: {
				winston: {
					transports: [
						new winston.transports.Console(),
						new winston.transports.File({ filename: "d:/winston.log" })
					]
				}
			}
`
How to use "bindings" to get nodeId or service name .... ? thank you
