### ISSUE TITLE
Add GraphQL Support

### ISSUE THREAD

**Issue by go4cas** [moleculerjs/moleculer-web#15]
Add GraphQL support to the API Gateway, with ability to consolidate responses from multiple services, bases on the GraphQL schema definition.

**Comment by zllovesuki** [comment]
Is this what you are looking for? https://github.com/MerlinLabs/moleculer-graphql#readme

**Comment by icebob** [comment]
My new implementation: https://github.com/moleculerjs/moleculer-apollo-server
