### ISSUE TITLE
Array body in action parameters

### ISSUE THREAD

**Issue by pibi** [moleculerjs/moleculer-web#150]
## Current Behavior

Moleculer web merges body, params and query from a request into the `req.$params` object. This works great with objects in body, but not if you are sending an array: 

here is an example using fetch and put:
```
fetch("http://localhost:3300/api/voli", {"credentials":"omit","headers":{"accept":"application/json, text/plain, */*","content-type":"application/json;charset=UTF-8","sec-fetch-mode":"cors"},"body":"[{\"EVVLID\":\"5980\",\"EVVLANRI\":\" \",\"EVVLFORN\":\"0\",\"EVVLSUPP\":\" \",\"EVVLOWRT\":\"  \",\"EVVLBLOC\":\"N\",\"EVVLRELE\":\"0\",\"EVVLBAGG\":\"N\",\"EVVLAAAP\":\"N\",\"EVVLDURA\":\"\",\"EVVLBRIT\":\"\"}]","method":"PUT","mode":"cors"});
```

this is the log from the API gateway:
```
[2019-11-05T17:02:26.924Z] INFO  spectrex360-56536/API: => PUT /voli
[2019-11-05T17:02:26.936Z] DEBUG spectrex360-56536/API:   Alias:    PUT /api/voli => voli.update
[2019-11-05T17:02:26.938Z] INFO  spectrex360-56536/API:    Call 'voli.update' action
[2019-11-05T17:02:26.964Z] DEBUG spectrex360-56536/API:    Params: { '0': { EVVLID: '5980', EVVLANRI: ' ', EVVLFORN: '0', EVVLSUPP: ' ', EVVLOWRT: '  ', EVV
LBLOC: 'N', EVVLRELE: '0', EVVLBAGG: 'N', EVVLAAAP: 'N', EVVLDURA: '', EVVLBRIT: '' } }
```

## Expected Behavior

I would expect to have the array I sent.  

## Context and additional info

I see the issue coming from the merge happening here: https://github.com/moleculerjs/moleculer-web/blob/master/src/index.js#L355-L361 I would suggest to switch  the merging order from
```
Object.assign(params, body, req.query);
```
to 
```
Object.assign(body, params, req.query);
```
Object.assign doesn't change the type of the first param, but it just use it has a target. Therefore the expected result if body is an array changes from:

```
> Object.assign({}, [1,2,3], {});
{ '0': 1, '1': 2, '2': 3 }
```
to:
```
> Object.assign([1,2,3], {id:1}, {test:'test'});
[ 1, 2, 3, id: 1, test: 'test' ]
```
With this, the final array will preserve its type, original length, can be iterate only on its original cells, but the other parameters will still be available as usual: 
```
> ctx.params.id
1
> ctx.params[2]
3
```

## Workaround

I'm working on a workaround with a custom function:
```
"PUT voli":
    async (req, res) => {
        req.$params = req.body;
        const result = await req.$service.broker.call("voli.update",req.body);
        res.end(result);
    },
```
but I'm not sure how to properly return the result and init the requestId:
```
[2019-11-05T17:26:40.530Z] WARN  spectrex360-25168/BROKER: Request 'api.rest' is timed out. { requestID: null, nodeID: 'spectrex360-25168', timeout: 10000 }
```

**Comment by pibi** [comment]
I've fixed the custom function for a proper workaround:
```
async function (req, res) {
	req.$params = req.body;
	const result = await req.$service.broker.call("voli.update",req.body);
	res.setHeader("Content-Type", "application/json; charset=utf-8");
	res.end(JSON.stringify(result));
},
```

**Comment by icebob** [comment]
Or just call the `sendResponse` method:
```js
async function (req, res) {
	try {
		const result = await req.$service.broker.call("voli.update",req.body);
		req.$service.sendResponse(req, res, result);
	} catch (ex) {
		this.sendError(req, res, ex);
	}
},
```
Other workaround if you turn off the merging logic in route options:
```js
	settings: {
		routes: [{
			path: "/api",
			mergeParams: false
		}]
	},
```

**Comment by icebob** [comment]
On the other hand, I will extend the `mergeParams` property in the next 0.9 beta that if it's a Function it will be called with these 3 parameters and you can define a custom merge function what you want.

**Comment by pibi** [comment]
thanks a lot for your response. I cannot turn off the merging logic because I have a ton of other actions which are using the merged params. would be handful to have an option at "endpoint level".

**Comment by icebob** [comment]
But if you turn off merging, you can use actions hooks which merge the parameters in the action side :)
