### ISSUE TITLE
MoleculerError is handled in API-Gateway at ALIAS level, but not in ROUTE level

### ISSUE THREAD

**Issue by luizeduardogiampaoli** [moleculerjs/moleculer-web#153]
Hello,
First of all, thank you for the amazing job with Moleculer! 

I am using a custom Moleculer error to indicate 503, service not available, like this:

```
class ServiceUnavailableError extends MoleculerError {
	constructor(msg, data) {
		super(msg || `Service is not available.`, 503, "SERVICE_N_AVAILABLE", data);
	}
}
```

Then I use it from inside a function like this:
```
var checkDbConnection = (req, res, next) => {
    
    if (AARMANService.checkDBConnection(req.body.sysGroup)) next();
    else {

        throw new ServiceUnavailableError(`The service is temporarily down.`, null);

    }

}
```

The code above is working just fine when I use it at ALIAS LEVEL, like this:

```
aliases: {
  "POST accounts": 
                 [
                  aarmanAC.checkDbConnection,
		  aarmanAC.checkForIdPresent,
		 "aarman.addAccount"
		],
			},
```
If db is not connected, then it returns the error 503 to the client just fine!

But, If I choose to use the same middleware in route level, like this:

```
use: [
 aarmanAC.checkDbConnection,
],

			aliases: {
				"POST accounts": [
					aarmanAC.checkForIdPresent,
					"aarman.addAccount"
				],
			},	`
```
It appears that node/moleculer does not CATCH the exception and node dies, like this

ServiceUnavailableError: The service is temporarily down.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aarm-api@1.0.0 dev: `moleculer-runner --repl --hot services`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aarm-api@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Is this expected behavior? It works at alias level, but not in route level. I tested and If I wrap var checkDbConnection = (req, res, next)  with try catch when using at route level just to test and then, the error is obviously catch and server does not die.

Any advice appreciated,
Thanks in advanced!
Luiz Eduardo Giampaoli

**Comment by icebob** [comment]
Hi, please create a simple repro example and I will check it.

**Comment by luizeduardogiampaoli** [comment]
Hello,
Thank you, I just tried to create a simple repro using https://codesandbox.io/s/moleculer-api-demo-ng3f5

Unfortunetely, I don´t now why the codesandbox project is ignoring completely any change I try to make in routes or aliases in "api.service.js". Any tips why it is not workings? Sorry.

For example:

```
settings: {
    port: 8080,
    routes: [
      {
        path: "/api",
        use: [accUtils.checkDbConnection],
        aliases: {
          "GET accounts": [accUtils.checkDbConnection, "greeter.Hello"]
        }
      }
    ],
    assets: {
      folder: "./public"
    }
  }
```
It keeps returning: 

```
{
  "name": "ServiceNotFoundError",
  "message": "Service 'accounts' is not found.",
  "code": 404,
  "type": "SERVICE_NOT_FOUND",
  "data": {
    "action": "accounts"
  }
}
```
Thanks,
Luiz

**Comment by icebob** [comment]
Sometimes codesandbox can't reload the server. In this try it manually:
![image](https://user-images.githubusercontent.com/306521/69190855-97fd2f00-0b21-11ea-9fa5-184d3ce5e6ab.png)

**Comment by luizeduardogiampaoli** [comment]
Hello @icebob,

Ok, now it works, and I was able to test it on the sandbox.

Unfortunetely (or fortunetely), I cannot reproduce the same error, server does not dies when I put the connect middleware that throws an exception in route level.

If I do the same thing in my local version, I get this:

```
ServiceUnavailableError: The service is currently unavailable
    at Service.checkDbConnection (G:\dev\giamcis\aarm-api\services\aarman\utils\aarman_api_checks.js:13:11)
    at next (G:\dev\giamcis\aarm-api\node_modules\moleculer-web\src\index.js:643:15)
    at G:\dev\giamcis\aarm-api\node_modules\moleculer-web\src\index.js:643:43
    at G:\dev\giamcis\aarm-api\node_modules\body-parser\lib\read.js:130:5
    at invokeCallback (G:\dev\giamcis\aarm-api\node_modules\raw-body\index.js:224:16)
    at done (G:\dev\giamcis\aarm-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (G:\dev\giamcis\aarm-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 503,
  type: 'SERVICE_NOT_AVAILABLE',
  data: null,
  retryable: false
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aarm-api@1.0.0 dev: `moleculer-runner --repl --hot services`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aarm-api@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\luizeduardo\AppData\Roaming\npm-cache\_logs\2019-11-20T00_50_53_391Z-debug.log
```

I will try to investigate this further and see if I can stop this error from happening.

Thanks you anyway!
Luiz

**Comment by icebob** [comment]
Try that not throw the error in middleware but call the `next(err)`.

**Comment by luizeduardogiampaoli** [comment]
Hello,
Got it, then I use an error handling middleware, I will refactor my code.

Thank you!
