### ISSUE TITLE
Prototype Pollution - NPM vulnerability

### ISSUE THREAD

**Issue by SushKenyNeosoft** [moleculerjs/moleculer-web#159]
=== npm audit security report ===                        

 Manual Review                                  
 Some vulnerabilities require your attention to resolve             
                                                                                
 Visit https://go.npm.me/audit-guide for additional guidance           

High            Prototype Pollution                                           

Package         lodash                                                        

Patched in      >=4.17.12                                                     

Dependency of   moleculer-web                                                 

Path            moleculer-web > lodash                                        

More info       https://npmjs.com/advisories/1065                             

found 1 high severity vulnerability in 1756082 scanned packages
1 vulnerability requires manual review. See the full report for details.

Can you guys update the dependency of lodash?

**Comment by AndreMaz** [comment]
It's updated in `v0.9-beta`. Use `npm i --save moleculer-web@next` to install the latest version.
Docs for the `v0.9` are here: https://moleculer.services/docs/0.14/moleculer-web.html

**Comment by SushKenyNeosoft** [comment]
Thank you so much sir
