### ISSUE TITLE
beta-6 missed this in routeHandler.

### ISSUE THREAD

**Issue by vora-bei** [moleculerjs/moleculer-web#162]
I have a problem with "use" and "alias" handler.
This is undefined.
I change 	this line 
 await composeThen(req, res, ...route.middlewares); 
to 
await composeThen.call(this, req, res, ...route.middlewares);
and
compose.call(...mws)(req, res, err => { 
to
compose.call(this, ...mws)(req, res, err => {

It's helped me.

**Comment by icebob** [comment]
If you need a pointer to service use the `req.$service`

**Comment by vora-bei** [comment]
Thanks. Is it a bug or change in the new version?

**Comment by icebob** [comment]
I've fixed the `this` in 0.9.0-rc1
