### ISSUE TITLE
Globaly disable colored log output (also for external modules)

### ISSUE THREAD

**Issue by nbvehbq** [moleculerjs/moleculer-web#172]
Options `logger.options.colors` used only for 'Console' logger. 
I want set it to `false`, but for external loggers this has no effect.

That`s why in the `moleculer-web` for example i see colored output when use Bunyan as external logger

In my opinion `logger.options.colors`  should be extendet to external loggers

What do you think?

**Comment by icebob** [comment]
Try adding the following codes to the top of `moleculer.config.js`:

```js
const kleur = require("kleur");
kleur.enabled = false;
```

Example: https://repl.it/@icebob/moleculer-dev-caller

**Comment by davidnussio** [comment]
I disabled moleculer-web colorized logs by setting FORCE_COLOR=0 as environment variable. [kleur documentation](https://github.com/lukeed/kleur#conditional-support)

**Comment by intech** [comment]
@davidnussio https://github.com/moleculerjs/moleculer-web/pull/212
what do you think about how to control the `FORCE_COLOR` variable from the `COLORS` variable supported in the moleculer?

**Comment by 1xtr** [comment]
> Try adding the following codes to the top of `moleculer.config.js`:
> 
> ```js
> const kleur = require("kleur");
> kleur.enabled = false;
> ```
> 
> Example: https://repl.it/@icebob/moleculer-dev-caller

It's not work for me. I use runner and Winston logger.
API Gateway logs are durty
`"message":"  \u001b[35m  POST\u001b[39m \u001b[36m/\u001b[39m\u001b[90m => \u001b[39mdata.main"`

even with `FORCE_COLOR=0`

```
"moleculer": "^0.14.29",
"moleculer-web": "^0.10.5",
```
