### ISSUE TITLE
New `addRoute` action

### ISSUE THREAD

**Issue by srosset81** [moleculerjs/moleculer-web#175]
I find the new `addRoute` method very helpful to build dynamic routes. However I think it would be even more helpful if it could be called from other services, so that they could choose to add routes on the fly. 

The `addRoute` method would just need to become an action.

I know it would be easy to create this action myself, but I'm building packages and so I would need this to be a standard ApiGateway behaviour.

I can submit a PR if this seems to be a good idea.

**Comment by icebob** [comment]
Implemented in https://github.com/moleculerjs/moleculer-web/commit/30a970889c047c5b358af536f9979a3e10b28ed5
