### ISSUE TITLE
All API Gateways in development don't regenerate auto alias routes 

### ISSUE THREAD

**Issue by NickClark** [moleculerjs/moleculer-web#177]
When you have more than one API Gateway, the regeneration of autoAliased routes does not occur on every service reload. So far I've pinned it down to the debouncing of `regenerateAllAutoAliases`.

At this point, I am assuming that the debounce function is being shared between in memory service instances due to the nature of how Moleculer uses Mixins.

(I personally prefer the class inheritance, class composition, and class decorator approaches, particularly since I'm using Typescript, and all the mixins are hard to track and get auto-completion for 😉 , but I digress)

I really love the overall library design and simplicity, thanks for all your hard work on this.

**Comment by icebob** [comment]
Hmm, nice catch. Are you running multiple API gateway with Node clusters? Or could you give me a repro example code?

**Comment by NickClark** [comment]
Right now I'm just running two different API gateways in development. One is a general API gateway,  the other is a dedicated auth server. In production they will run in their own docker instances, so no problem there.  Perhaps I'm misusing it. Either way, I know normally you would run these servers in separate nodes, so you wouldn't see this issue, even if you were scaling up. 

It's easily reproducible though. Just have the same runner startup two different services that both extend ApiGateway and use autoAliases. Only one will get updates. If still needed, I'll try to make a simple reproduction.
