### ISSUE TITLE
Enhancements to Logs

### ISSUE THREAD

**Issue by erlichmen** [moleculerjs/moleculer-web#204]
We notice that In v0.10 you can control the log level the request/response will be logged which is a nice addition.
I would like to suggest to be able to control the log level of the request/response also PER route level. When working with health checks we define a route that is hammered every 5 seconds and that creates unnecessary logs noise.

Also, it would be nice if the color output will also be turned off by demanded as not all of the log output support TTY.

PR Welcomed?

**Comment by intech** [comment]
@erlichmen disabling color logs is available in [moleculer configuration](https://moleculer.services/docs/0.14/logging.html#Console-default).

There are currently no settings for flexible configuration of logging in the moleculer-web.

> PR Welcomed?

Always welcome!
I think we should look at an example of the implementation of the [log level settings](https://moleculer.services/docs/0.14/logging.html#Log-Level-Setting)

**Comment by icebob** [comment]
@erlichmen yeah, good idea. PR's welcomed. As @intech said, you can disable colors in broker option logger settings.
