### ISSUE TITLE
Accessing CORS settings from env

### ISSUE THREAD

**Issue by intech** [moleculerjs/moleculer-web#207]
I propose to discuss adding such a possibility.

The first argument in favor of adding settings via environment variables is to move away from the anti-pattern of using url in the code. A fairly dynamic change to origin, it is logical to leave the rest of the settings static.

Second argument for the convenience of separating environments
**development:** `CORS=*`
**production:** `CORS=url1,url2` (separated by commas)

@icebob It is necessary to define the namespace for the moleculer-web by analogy with MOL__ for the moleculer

**Comment by icebob** [comment]
Why not use simply:
```js
settings: {
    cors: {
        origin: process.env.CORS_ORIGIN || "*",	
    }
}
```

**Comment by intech** [comment]
Can, so the `MOL_` settings can be changed :)
