### ISSUE TITLE
file streaming via alias has an empty $params object

### ISSUE THREAD

**Issue by fjeglinski** [moleculerjs/moleculer-web#211]
Hi there,

currently we have a problem with file streaming when we using a NATS server for service communication. When we set up the application on our local machine everything works as expected.

The problem is that while using NATS the $params object is empty, although we defined this param as part of an alias. Like described here: https://moleculer.services/docs/0.14/moleculer-web.html#File-upload-aliases

And due to the empty $params object the validation for the stream receiving function fails.

The call of  
```typescript
'POST /event/:id': 'stream:event.addFile',
```
is correct because the code is invoked correctly on localhost.

This is our API Gate Way Code:
```typescript
                             {
                            path: '/files',
                            authorization:  true,
                            autoAliases: true,
                            mergeParams: true,
                            mappingPolicy: 'restrict',
                            bodyParsers: {
                                json: false,
                                urlencoded: false
                            },
                            aliases: {
                                'POST /event/:id': 'stream:event.addFile',
                            }
                        },
```

And this is the corresponding `addFile` Action:
```typescript
      addFile: {
                    params: {
                        id: 'string'
                    },
                    async handler(ctx: Context<{ $params: { id: string }, headers: any }, { $statusCode: number }>): Promise<void> {
                    ...
                    }
```

Every help is appreciated =). Thanks guys!

**Comment by icebob** [comment]
Please create a repro repo.

**Comment by fjeglinski** [comment]
Of Course: https://repl.it/repls/AlarmingGiganticComputerscience#index.js

**Comment by intech** [comment]
this is my repl =)
reference: https://github.com/moleculerjs/moleculer-web/issues/188

**Comment by fjeglinski** [comment]
> this is my repl =)
> reference: #188

Yes! Basically we have the same problem :D

**Comment by intech** [comment]
I unfortunately did not solve this problem completely, but refused to use stream in my project.

You need to think about the design of the moleculer-web and work with parameters in streams, there is some separation that is not obvious when working.

**Comment by intech** [comment]
@fjeglinski yes, there is an unobvious action in which we lose access to the parameters.

**Comment by icebob** [comment]
0.10.0-beta4: https://github.com/moleculerjs/moleculer-web/blob/master/CHANGELOG.md#multipart-fields--url-params
