### ISSUE TITLE
`callOptions.timeout` takes precedence over `action.timeout`

### ISSUE THREAD

**Issue by SupremeTechnopriest** [moleculerjs/moleculer-web#231]
If you set `callOptions.timeout` on the routes:

```javascript
callOptions: {
  timeout: 10000
}
```

and try to override it for a specific action:

```javascript
action: {
  timeout: 30000,
  params: { ... },
  async handler (ctx) { ... }
}
```

The `callOptions` value takes precedence.  I would expect to be able to override this behavior per route.

**Comment by icebob** [comment]
The `callOptions` timeout has always precedence. 
1. `timeout` in ctx calling options (the `callOptions.timeout set it)
2. `timeout` in action definition
3. `requestTimeout` in broker options.

**Comment by SupremeTechnopriest** [comment]
Ah makes sense.  Its because callOptions are passed directly to the call function.  I have a bunch of different route groups in my project. About 6 different sets of routes.  What I would like to be able to do is set a default timeout for the group of routes and be able to override that per action.  Maybe callOptions is not the place to do that.  Is there a `requestTimeout` option directly on the routes that we can set so that action values can override them?

**Comment by icebob** [comment]
I think, you can't do that. Only `callOptions` is configurable in the routes.

**Comment by SupremeTechnopriest** [comment]
Okay no problem.  I got my backend to stop timing out by upping the callOptions timeout so Im good to go.  This would just be a nice to have I think.  You can feel free to close this.
