### ISSUE TITLE
Alias doesn't work

### ISSUE THREAD

**Issue by JulianXin216** [moleculerjs/moleculer-web#239]
I am learning to use moleculer.
I set the aliaes ine the routes setting .
```js
 routes:[{
         path: "/api",
	whitelist: ["**"],
	aliases:{
		"abc":"status.systems",
		"count": "basic.count"
	},
	autoAliases: true
}]
```
But the address `http://localhost:3010/api/abc` got an error;
```js
{
    "name": "ServiceNotFoundError",
    "message": "Service 'abc' is not found.",
    "code": 404,
    "type": "SERVICE_NOT_FOUND",
    "data": {
        "action": "abc"
    }
}.
```
I did somthing wrong?

I used  VSCode to debug.

moleculer version:0.14.11
moleculer-web version:0.9.1

**Comment by AndreMaz** [comment]
The [`ServiceNotFoundError`](https://moleculer.services/docs/0.14/errors.html#ServiceNotFoundError) means that the service actions is not registered. 

You can use [moleculer-repl](https://moleculer.services/docs/0.14/moleculer-repl.html#List-actions) to see what actions are available/exposed.

**Comment by intech** [comment]
Does the service have a version? Then you need to specify it at the beginning of the service name
```js
	aliases:{
		"abc":"v1.status.systems",
		"count": "v1.basic.count"
	},
```

**Comment by JulianXin216** [comment]
> Does the service have a version? Then you need to specify it at the beginning of the service name
> 
> ```js
> 	aliases:{
> 		"abc":"v1.status.systems",
> 		"count": "v1.basic.count"
> 	},
> ```

No version.
After I cleaned the node_modules and  reinstalled the modules. It works now.  Maybe something wrong with my computer.
