### ISSUE TITLE
Documentation has some problems for auto-aliases

### ISSUE THREAD

**Issue by unitythemaker** [moleculerjs/moleculer-web#242]
Hello,
I noticed that there is a problem in the docs. [Here](https://moleculer.services/docs/0.14/moleculer-web.html#Auto-alias)
In this section:
```javascript
whitelist: [
                    "posts.*",
                    "test.*"
                ],
```
That should be v2.posts.* instead of it. I tried it on my local then it didn't create the aliases. So I saw this issue and fixed it: #239 
But if you can fix it, it will be awesome. I don't know where the docs is (which repo and which path). If you can let me know, I can create a PR too.
Thanks.

**Comment by unitythemaker** [comment]
Also I'd like to add that it doesn't create alias for /api/v2/... it creates as /api/service_name
You can see this screenshot: 
![flameshot_imgur](https://i.imgur.com/IYIa6FC.png)
![flameshot_imgur](https://i.imgur.com/XYgnX4x.png)

**Comment by unitythemaker** [comment]
I also figured that when I comment the settings: rest: it creates the alias for /api/v2/... and that solved my problem. However I want you to fix it in the docs.
![flameshot_imgur](https://i.imgur.com/mG3jVZk.png)
![flameshot_imgur](https://i.imgur.com/adeGpkr.png)

**Comment by AndreMaz** [comment]
>I don't know where the docs is (which repo and which path). If you can let me know, I can create a PR too.

Hi @unitythemaker the docs for API gateway are located here: https://github.com/moleculerjs/site/blob/master/source/docs/0.14/moleculer-web.md

You can clone the site repo and update the docs. More info [here](https://github.com/moleculerjs/site#development)

**Comment by unitythemaker** [comment]
Thanks, I created a PR: moleculerjs/site#142
