### ISSUE TITLE
Authorization With Data base connection

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer-web#263]
I have already created  moleculer js project with API Gateway. I need to implement   Data base connection inside authenticate() function . But other service mixins with Data base connection . How i connected to data base inside API ->authenticate() service . If there any specific method to add this DB connection

**Comment by icebob** [comment]
in `authenticate` method is better to call a service which does the check against DB, instead of adding DB connection inside authenticate.
