### ISSUE TITLE
API service fails to spin up in Docker

### ISSUE THREAD

**Issue by rishighan** [moleculerjs/moleculer-web#267]
Hello, I'm using the [Typescript template](https://github.com/moleculerjs/moleculer-template-project-typescript)

I have a single service called `comicvine`, and the service definition looks like this:
https://github.com/rishighan/comicvine-service/blob/8dc5daf3e0c618531c7beb0ceb2d9afdb6111242/services/comicvine.service.ts#L14

The Dockerfile:
```Dockerfile
FROM node:12-alpine

# Working directory
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --silent

# Copy source
COPY . .

# Build and cleanup
ENV NODE_ENV=production
RUN npm run build \
 && npm prune

# Start server
CMD ["npm", "start"]
```

With this configuration, when I do a `docker build . -t frishi/comicvine-service` and a `docker run -it frishi/comicvine-service`, the Docker image fails to start up with:

```terminal
BROKER: ServiceBroker is stopped. Good bye.
```

I tried setting the `ENV SERVICES=services` environment variable in the `Dockerfile` and it seems to have no effect.
What gives?

**Comment by icebob** [comment]
https://moleculer.services/docs/0.14/faq.html#Why-the-broker-exits-without-any-error-when-I-start-my-service

**Comment by rishighan** [comment]
Thanks for the link, that was it.
