### ISSUE TITLE
Performance improvement - Minor change

### ISSUE THREAD

**Issue by kcarthic** [moleculerjs/moleculer-web#285]
@icebob Can improve performance of routes lookup
File: src/index.js
Line: 185
You can improve lookup speed by ~2x by changing
`if (url.startsWith(route.path))`
with
`if (url.indexOf(route.path)>-1)`

**Comment by icebob** [comment]
the two lines not the same. `>-1` not equal with `startsWith`. 
Can you substantiate the increase in performance?
