### ISSUE TITLE
Routes with same path ignored after 0.9.1

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [moleculerjs/moleculer-web#293]
I think there is an hidden breaking change between version 0.9.1 and 0.10.0 since routes with the same path are not correctly loaded:

```javascript
  settings: {
    port,
    routes: [{
       path: '/api',
       aliases: {
              'GET /diagnostic': `diagnostic.getStatus`,
        }
    }, {
       path: '/api',
      aliases: {
              'GET /hello': `hello.hi`,
        }
       // ...other settings for group
    }],
    use: [headersParser]
  },
``` 

Calling each of the aliases on 0.9.1 resolved correctly the endpoint and the action. With the 0.10.0 returns always a 404.

**Comment by intech** [comment]
Need to set a unique name for routes, read [this changelog](https://github.com/moleculerjs/moleculer-web/releases/tag/v0.10.2)

**Comment by giovanni-bertoncelli** [comment]
Ok thank you
