### ISSUE TITLE
apply autoAliases only where there is a rest setting.

### ISSUE THREAD

**Issue by swkim0572** [moleculerjs/moleculer-web#296]
Dynamic routing with autoAliases

It seems good to apply only those with rest configuration.

Several services are using a common mixin.

Those were not intended to apply autoAliases.

But if you use autoAliases, a router is created for all previous actions.

I think that actions to apply autoAliases should use rest configuration

The following settings are required
autoAliases: { restOnly: true }

In addition, I would like to be able to configure middleware in rest configuration.

**Comment by icebob** [comment]
Dynamic routing adds only actions where `rest` is configured in action definition:
https://github.com/moleculerjs/moleculer-web/blob/65b7addddc3dc34856d2a3bf6fe202664b2e033c/src/index.js#L1495

**Comment by swkim0572** [comment]
thank you for your kind
