### ISSUE TITLE
Query string number params are not converted

### ISSUE THREAD

**Issue by alvarocantador** [moleculerjs/moleculer-web#305]
Following the sample math.service.js and calling it http://0.0.0.0:3000/math/mult?a=1&b=2 returns a validation error:

```json
{"name":"ValidationError","message":"Parameters validation error!","code":422,"type":"VALIDATION_ERROR","data":[{"type":"number","message":"The 'a' field must be a number.","field":"a","actual":"1","nodeID":"mac-542187-70487","action":"math.mult"},{"type":"number","message":"The 'b' field must be a number.","field":"b","actual":"2","nodeID":"mac-542187-70487","action":"math.mult"}]}
```

Node version: 16.13.1
Moleculer: 0.14.19
Moleculer Web: 0.10.4

**Comment by alvarocantador** [comment]
@icebob Do you think that is a good idea to modify the [parseQueryString](https://github.com/moleculerjs/moleculer-web/blob/master/src/index.js#L944) method? I can try do something there

**Comment by icebob** [comment]
No, the parse method works well, you should change the `params` validators in `mult` action as adding `convert: true`. In this case, validator will convert the string values to number and won't throw validation error.
