### ISSUE TITLE
Allow for array query strings

### ISSUE THREAD

**Issue by daniel-white** [moleculerjs/moleculer-web#309]
I have a OAS 3.1 spec that has a query parameter that is an array but uses the non-exploded form such as `?type=main,secondary`. The gateway using `parse` from [ljharb/qs](https://github.com/ljharb/qs) & `parseQueryString` does not seem to account for these additional options and the param ends up in a couple different ways

1. `?type=main,secondary` => `"type": "main,secondary"` => fails to validate
2. `?type=main` => `"type": "main"` => fails to validate
2. `?type=main&type=secondary` => `"type": ["main", "secondary"]` => validates fine

My param config:
```
{
  type: 'array',
  items: { type: 'string' },
  uniqueItems: true,
  minItems: 1,
  convert: true
}
```

Should `parseQueryString` be smarter and respect some other OAS options?

The [docs are lacking ](https://moleculer.services/docs/0.14/moleculer-web.html#Query-string-parameters) and just indicate to read up on [ljharb/qs](https://github.com/ljharb/qs)

**Comment by intech** [comment]
`?type[]=main&type[]=secondary` for more information read [this thread](https://stackoverflow.com/questions/15854017/what-rfc-defines-arrays-transmitted-over-http)

**Comment by daniel-white** [comment]
Also: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#style-examples

**Comment by daniel-parakey** [comment]
@intech is there a reason we are not allowed to specify this ourselves? For example through passing `qsOptions` in `settings` and using it [here](https://github.com/moleculerjs/moleculer-web/blob/f375dbb4f8bff8aa16e95024e5c65463b626fa45/src/index.js#L956)?

**Comment by daniel-parakey** [comment]
@intech thoughts? https://github.com/moleculerjs/moleculer-web/pull/326
