### ISSUE TITLE
Q&A: How can I remove the service name from the api endpoint? 

### ISSUE THREAD

**Issue by nnthuan** [moleculerjs/moleculer-web#315]
Q&A: How can I remove the service name from the API endpoint? 

When run service, API endpoint like this

`/${SERVICE NAME}/products/:id` <-- Auto

Expected: `/products/:id`

---

"moleculer": "^0.14.24",
"moleculer-web": "^0.10.4",

**Comment by intech** [comment]
@nnthuan How exactly are you configuring the REST?

**Comment by nnthuan** [comment]
Hi @intech

```js
export default class ApiService extends Service {

  public constructor(broker: ServiceBroker) {
    super(broker);
    this.parseServiceSchema({
      name: "ProductService",
      mixins: [ApiGateway],
      // More info about settings: https://moleculer.services/docs/0.14/moleculer-web.html
      settings: {
        port: process.env.PORT || 3000,
        routes: [{
          path: "/",
          ...
          }]
       },

      actions: {
               getProduct: {
                   rest: "GET /products/:id",
                   ....
               }
       }
```

Expected: `http://localhost:3000/products/:id`

Actual: `http://localhost:3000/ProductService/products/:id`

I don't want to have `/ProductService` in my endpoint.

**Comment by nnthuan** [comment]
I see doing it manually through the alias, but API Gateway publishes APIs from various services, which is quite exhausting with a large amount.

Is there a setting that applies to all?

**Comment by intech** [comment]
@nnthuan Generation automatically goes according to the `rootApiPath/serverSettingsRestPath/action` template. By adding step by step to the root settings of the path, setting the service path (including the version and name or option specified in the REST settings), the action path from its name (or from the REST option).

**Comment by nnthuan** [comment]
Resolved

```js
{
   settings: {
      rest: '/',
   }
}
```
