### ISSUE TITLE
Response headers affectation

### ISSUE THREAD

**Issue by furanzujin** [moleculerjs/moleculer-web#323]
Hello,

We encountered a crash of the HTTP gateway during the assignment of the response headers.
This error occurred because of invalid characters in one of the header keys.

Several ways have been identified to avoid this crash:
* sanitizing the keys/values at assignment time in the $responseHeaders variable
* sanitizing the keys/values through the onAfterCall hook

However, we believe that crashes could be avoided more globally by securing the `sendResponse` and `sendError` processes.

Do you want us to propose a change to the `moleculer-web` component to implement these operations?
If so, we would like to include a log (warn or error) and skip the assignment of the problematic header.

Would this be acceptable to you?

**Comment by icebob** [comment]
Yeah, please create a PR with your proposed fix.

**Comment by furanzujin** [comment]
Hello @icebob,

Sorry for the delay; you'll find a pull request here to avoid process crashes on invalid header character assignments.
