### ISSUE TITLE
HTTP 2 support

### ISSUE THREAD

**Issue by mrcheidel** [moleculerjs/moleculer-web#33]
Hello,
I would like add a request for enhancement HTTP 2 support protocol
Congratulations for this framework!

**Comment by icebob** [comment]
Thank you!

**Comment by zllovesuki** [comment]
As I understand it, nodejs core already has a working implementation of http2 server: https://nodejs.org/api/http2.html

**Comment by icebob** [comment]
Yes, but this is quite different, so I'm afraid, it should be implemented in a new `moleculer-web2` repo instead.

**Comment by icebob** [comment]
Coming in 0.9.0

**Comment by aliazlan4** [comment]
0.9.0 is still not on npm registry. When the new version will be deployed? Is http2 fixed in 0.9.0?

**Comment by icebob** [comment]
Hi, 0.9.0 beta is released. Install it with `npm i moleculer-web@next`

**Comment by aliazlan4** [comment]
I have checked 0.9.0beta2 but http2 is still not working. Is there any further configuration to do beside http2 = true in api gateway service?

**Comment by icebob** [comment]
did you set ssl, too?

**Comment by aliazlan4** [comment]
No, SSL is being handled by my load balancer, its not implemented in application.

**Comment by icebob** [comment]
If I remember correctly, it works only with SSL.

**Comment by truesteps** [comment]
Any updates to http2 support?

**Comment by icebob** [comment]
HTTP2 only works with SSL certs.
