### ISSUE TITLE
Allow define action type in auto aliases (rest action param)

### ISSUE THREAD

**Issue by francisfontoura** [moleculerjs/moleculer-web#348]
In service mixed with `molecular-web` service, you can define "type" of action when defining route aliases:
```js
settings: {
  routes: {
    'POST /multipart': 'multipart:api.handleMultipart', // `multipart` is the "type"
    'PUT /stream': 'stream:api.handleStream', // `stream` is the type
  }
}
```
But in `autoAliases` (`rest` property in action configuration), you can't. It will be nice if we can do something like this:
```js
actions: {
  handleStream: {
    rest: { type: 'stream', method: 'PUT', path: '/stream' }
  }
}
```

**Comment by icebob** [comment]
After checking the source, I think your propose should work. Did you try it?

**Comment by francisfontoura** [comment]
:man_facepalming: I was betrayed by TypeScript. After turning off type checking, it actually worked. Anyway, it would be better to officially support it in the RestSchema interface, somehow handle it in parseActionRestString, and document it. Nevertheless, my issue is resolved, and I appreciate your response.
