### ISSUE TITLE
Middleware - context object

### ISSUE THREAD

**Issue by molobala** [moleculerjs/moleculer-web#36]
Since route middlewares signature is this : ` function(req, res, next) {...} ` , I wondered how to access the ctx object and add meta data to it

**Comment by icebob** [comment]
Middlewares are called before Context creating. You can only manipulate `req` and `res` in middlewares.
You should use `onBeforeCall` hook to load context meta: http://moleculer.services/0.12/docs/moleculer-web.html#Route-hooks

**Comment by molobala** [comment]
I also noticed that , in case authorization is activated, `authorize` method is called after, aliases level middlewares

**Comment by icebob** [comment]
Yes, it's not available currently.

**Comment by icebob** [comment]
Solving in 0.8.x

**Comment by molobala** [comment]
Great! 

Will check it

**Comment by icebob** [comment]
Issue is fixed & released in 0.8.0
