### ISSUE TITLE
When alias has an associated handler, it doesn't authorize the request.

### ISSUE THREAD

**Issue by kuber-** [moleculerjs/moleculer-web#41]
Hi there,

When alias handler is available, it returns on line 503 (pls. see link below). This skips preActionCall call. Which in turn skips authorize call, amongst other helpful function like onBeforeCall.

https://github.com/moleculerjs/moleculer-web/blob/08cdc3c329a9922e88da66a8b803b1c74878a287/src/index.js#L503

**Comment by felipegcampos** [comment]
Hey bro, refer to issue #42 I just created. I think it can help to solve the problem for now. Regards.
