### ISSUE TITLE
Cors with multiple origins returning error

### ISSUE THREAD

**Issue by felipegcampos** [moleculerjs/moleculer-web#43]
Trying to do something like:

```
cors: {
  origin: ['http://localhost:3000', 'http://localhost:4000'],
  methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'],
  credentials: true,
},
```

I'm getting the following error:

> login:1 Failed to load [my_page]: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:3000, http://localhost:4000', but only one is allowed. Origin 'http://localhost:4000' is therefore not allowed access.

Reading through I think the solution would be something like:

```
} else if (Array.isArray(route.cors.origin)) {
  const origin = req.headers['origin'];
  if(route.cors.origin.indexOf(origin) > -1) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Vary", "Origin");
  }
}
```
rather than the current one:

https://github.com/moleculerjs/moleculer-web/blob/08cdc3c329a9922e88da66a8b803b1c74878a287/src/index.js#L922-L925

Following, a reference on how HapiJs is doing it:
https://github.com/hapijs/hapi/blob/574d768b2648a6b2e404225d2771cb0220ed9d97/lib/cors.js#L48-L55

I am creating a PR and adding the wildcard to origins such as "localhost:*". Let me know if it's ok for you.

**Sources:**
https://blog.crashtest-security.com/multiple-values-access-control-allow-origin-3c7cafc8c5c0
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Allow-Origin

**Comment by felipegcampos** [comment]
Some additional information about cors + origin:

https://stackoverflow.com/questions/46086997/should-i-send-any-access-control-allow-origin-header-to-non-allowed-origins-in-t
https://stackoverflow.com/questions/42239643/when-does-firefox-set-the-origin-header-to-null-in-post-requests/42242802#42242802

**Access-Control-Allow-Origin** shouldn't be set if the preflight request can't find the **Origin** within the request header. It could return 404 - Origin Not Found

I am adding it to my PR.

**Comment by icebob** [comment]
Thanks, please create a PR with fixes.

**Comment by felipegcampos** [comment]
Done, can you check pls?
