### ISSUE TITLE
How to set the server's timeout more than the standard 2 minutes?

### ISSUE THREAD

**Issue by JeStasG** [moleculerjs/moleculer-web#47]
And in middlevare I tried:
`
 use: [
                cookieParser(),
                function(req, res, next){
                    req.socket.server.setTimeout(600000);
                    next();
                }
            ]
`
The code in the hook created()
`this.server.setTimeout(600000);`
The result was not given
Tell me, please, the more correct method!?

**Comment by icebob** [comment]
Did you try it in the `started()`?

**Comment by JeStasG** [comment]
Yes, I tried it in started() too...
Logger writes to the console, everything is as expected. The hooks of the router also work out, but something breaks the connection a multiple of 2 minutes.

**Comment by icebob** [comment]
Feel free to open back if you think the issue is related to moleculer-web.
