### ISSUE TITLE
Request headers are not being passed to a context for any further processing.

### ISSUE THREAD

**Issue by Shal10** [moleculerjs/moleculer-web#49]
I am making a REST call from one web service to a node js microservice but request headers of the REST such as x-b3-traceid, x-b3-spanid etc. does not get passed thru molecular-web for tracing.

**Comment by icebob** [comment]
You should set request headers in route hooks: https://moleculer.services/0.12/docs/moleculer-web.html#Route-hooks

**Comment by Shal10** [comment]
Thanks @icebob! Yes, worked for me using API Gateway - route hooks! 💯 

`routes: [{
			path: "/api",
			onBeforeCall(ctx, route, req, res) {
                                ctx.parentID = req.headers["x-b3-spanid"];
				ctx.requestID = req.headers["x-b3-traceid"];
            }`

**Comment by oldeng** [comment]
how can i get request and response Object methods in actions methods

**Comment by oldeng** [comment]
i just want to get file data in request
