### ISSUE TITLE
Enable force https redirect 

### ISSUE THREAD

**Issue by cpankaj** [moleculerjs/moleculer-web#50]
Need support to redirect all http requests to https for assets.
Using a middleware for force redirect only act on the services and not the asset load.

**Comment by icebob** [comment]
You can use [some similar solution](https://github.com/Bizzby/force-https/blob/master/index.js) as middleware

**Comment by intech** [comment]
@v-vovk-edvantis check [this package](https://www.npmjs.com/package/redirect-https) please.
