### ISSUE TITLE
assets not work

### ISSUE THREAD

**Issue by roytan883** [moleculerjs/moleculer-web#55]
as Doc , i config it like this:
```
assets: {
          // Root folder of assets
          folder: "./public",

          // Options to `server-static` module
          options: {}
        },
```
Then i write a index.html in `./public/index.html`, But i try those URL, all can't get the index.html
```
/index.html
/api/index.html
/api/public/index.html
/api/public/api/public/index.html
/api/api/public/index.html
```

**Comment by icebob** [comment]
Please show the full settings.

**Comment by roytan883** [comment]
To fix this issue, i create my own static middleware:
```
let staticMiddleware = function (req, res, next) {
  if (_.startsWith(req.url, '/api/static')) {
    //must change the url prefix to map to static folder root
    let oldUrl = req.url
    req.url = _.replace(req.url, '/api/static/', '/');
    console.log(`staticMiddleware change req.url: [${oldUrl}] -> [${req.url}]`)
    serve(req, res, finalhandler(req, res))
  }
  else {
    next()
  }
}
```
To enable Dir access, need modify the error hander:
```
onError(req, res, err) {
          if (!_.startsWith(req.url, '/api/static') && _.endsWith(req.url, '/')) {
            res.writeHead(302, {
              'Location': '/api/static' + req.url
            })
            res.end();
            return
          }
          res.setHeader("Content-Type", "text/plain");
          res.writeHead(err.code || 500);
          res.end('Error: ' + err.message);
        }
```

**Comment by roytan883** [comment]
```
 mixins: [ApiService],
 settings: {
   path: "/api",
   assets: {
          // Root folder of assets
          folder: path.join(__dirname, "./public"),

          // Options to `server-static` module
          options: {}
        },
```

**Comment by icebob** [comment]
It should work with this settings. Similar code in [examples](https://github.com/moleculerjs/moleculer-web/blob/master/examples/www/index.js#L54) and it works.

**Comment by roytan883** [comment]
and i found that `// Global-level middlewares` in settings is not really GLOBAL. It only handle request from `/api`

**Comment by roytan883** [comment]
@icebob 
> It should work with this settings. Similar code in examples and it works.
which url should i use to access `index.html` in `assets` folder ? 
/index.html 
/api/index.html
/api/assets/index.html

**Comment by icebob** [comment]
if you have a root `path: "/api", in this case /api/index.html. If no root path, just `/index.html`.

**Comment by roytan883** [comment]
OK, it works. But root path is `/api`, the access path need to be `/index.html`.

**Comment by icebob** [comment]
Hmm it's weird. Maybe it doesn't consider the `path` setting.

**Comment by roytan883** [comment]
But i think it is great. `asserts` path should not start with `/api`. Please do not change it :)

**Comment by roytan883** [comment]
I think the `assets` not use `compression` , because the root level middleware is not **GLOBAL** so far, which only handle `/api`

**Comment by icebob** [comment]
Global middlewares are added to `routes` only, not for global static serving. In this case you'd better make a `path: "/"` route where you can add compression & serve static middlewares instead of global `assets`.

**Comment by roytan883** [comment]
so the global `assets` can't use compression ?

**Comment by roytan883** [comment]
why not make the `Global middlewares` apply to **GLOBAL** ? (I mean on `/`)
It not make any sense, because the `routes` already have its own `// Route-level middlewares.`

So far, if `setting` the root path is `/api`,  then all i can hook is on this path, all other `/xxx` can't handle. Its not extendable.

**Comment by roytan883** [comment]
So far, I found the only interface I can hook to **GLOBAL** is `onError` ......

**Comment by roytan883** [comment]
So the right way to use this library is :
root path: `/`
route1: `/api`
route2: `/assets`
If it is right, then the global `assets` setting does not make any sence.

**Comment by icebob** [comment]
No the route can be `/` too.

root path: /
route1: /api
route2: / (must be the latest)

**Comment by icebob** [comment]
Can I make an example settings?

**Comment by roytan883** [comment]
yes, please.

**Comment by roytan883** [comment]
not work ......
here is code:
ApiGatewayService ->
```
class ApiGatewayService extends Service {
  constructor(broker) {
    super(broker);
    this.parseServiceSchema({
      name: "apiGateway",
      mixins: [ApiGateway],

      settings: {
        path: "/",

        port: 10300,

        use: [
          compression(),
          // Security
          // helmet(),
        ],

        routes: [
          /**
           * API route
           */
          {
            path: "/api",
            mappingPolicy: "all",
            // Use bodyparser modules
            bodyParsers: {
              json: { limit: "2MB" },
              urlencoded: { extended: true, limit: "2MB" }
            },
          },

          /**
           * Static route
           */
          {
            path: "/",

            use: [
              // Serve static
              ApiGateway.serveStatic("./public"),
            ],
          }
        ]
      }
    });
  }
  async serviceCreated() {
    this.logger.info(`${this.name} Service created.`);
  }
  async serviceStarted() {
    this.logger.info(`${this.name} Service started.`);
  }
  async serviceStopped() {
    this.logger.info(`${this.name} Service stopped.`);
  }
}
module.exports = ApiGatewayService;
```
main.js
```
//new moleculer broker
let broker = new ServiceBroker({
  namespace: config.namespace,
  nodeID: config.nodeID,
  requestTimeout: config.natsTimeout,
  logger: console,
  logLevel: config.logLevel,
  logFormatter: logFormatter,
  transporter: {
    type: "NATS",
    options: {
      url: config.natsHost,
      // user: "admin",
      // pass: "123"
    }
  },
  statistics: true,
});

//load service
broker.loadService(path.join(__dirname, `./services/${config.service}`, '/index.js'))

//start
broker.start().then(() => {
  console.warn(`=====[${config.nodeID}]=====>>>>> started`)
})
```

open `/index.html` return
```
{
  "name": "MoleculerError",
  "message": "Not found",
  "code": 404
}
```

a strange thing is `Service created` never print. But my other services printed, does ApiGateway not support by `loadService`?

**Comment by icebob** [comment]
Which versions?

**Comment by icebob** [comment]
> a strange thing is Service created never print. But my other services printed, does ApiGateway not support by loadService?
You should set functions in `parseSchema`

```js
            created: this.serviceCreated,
            started: this.serviceStarted,
            stopped: this.serviceStopped,
```

**Comment by roytan883** [comment]
Now the `/api` works weird:
```
      name: "apiGateway",
      mixins: [ApiGateway],
      settings: {
        path: "/",
        port: 10300,
        use: [
          compression(),
        ],

        routes: [
          {
            path: "/api",
            bodyParsers: {
              json: { limit: "2MB" },
            },
          },
```
call `curl -H "Content-Type:application/json" -X POST -d '{"name": "roy"}' http://127.0.0.1:1030/api/demo/welcome` return:
```
{
  "name": "MoleculerError",
  "message": "Not found",
  "code": 404
}
```
But call `curl -H "Content-Type:application/json" -X POST -d '{"name": "roy"}' http://127.0.0.1:1030//api/demo/welcome` it works, return:
```
"Welcome, roy :)"
```
you see, the `//` works ...

**Comment by icebob** [comment]
Which versions are you using?

**Comment by roytan883** [comment]
version: 
```
"name": "moleculer-web",
  "version": "0.6.4",

```

**Comment by icebob** [comment]
Try it:
```js
      name: "apiGateway",
      mixins: [ApiGateway],
      settings: {
        path: "",
```

**Comment by roytan883** [comment]
I just installed it yesterday

**Comment by roytan883** [comment]
OK, set `path: "",` make both `/api` and static assets work

**Comment by icebob** [comment]
Great, I will fix this `path: "/"` issue in the next version

**Comment by roytan883** [comment]
Thanks for your help 👍
