### ISSUE TITLE
Tilde character `~` is replaced by `$` breaking legit paths

### ISSUE THREAD

**Issue by DrecDroid** [moleculerjs/moleculer-web#56]
This line is breaking some valid paths:
https://github.com/moleculerjs/moleculer-web/blob/513488e0892491e9d4c3dc73fa9b1b9b40161692/src/index.js#L488

It breaks paths like this for example:
`http://127.0.0.1:3000/api/posts/sR0FmQLsxKwVas1~bvy9H`

`~` is an unreserved character according to [RFC3986](https://www.ietf.org/rfc/rfc3986.txt)

**Comment by icebob** [comment]
It replaced to enable to call internal services like `$node.services`. In this case need a setting to disable this replacing.
