### ISSUE TITLE
What is the preferred way of sending errors to the api gateway?

### ISSUE THREAD

**Issue by kheide** [moleculerjs/moleculer-web#57]
When using MoleculerError to create errors in my services which are in turn sent back to the api-gateway it exclusively sends http status code 200 back to the client regardless. I've tried adding a global onError handler aswell, but to no avail. When I return errors from moleculer-web (authorize function) it sends them back to the client correctly so I am assuming this is an issue with how data is being exchanged between the api gateway and the services and how errors are picked up. 

What is the best practice here?

**Comment by icebob** [comment]
Could you show the code part where you throw an Error? Do you use either `throw new MoleculerError()` or  `return Promise.reject(new MoleculerError())` instead of `return new MoleculerError()`?

**Comment by kheide** [comment]
Here is an example; 

from users.js
` try {
    user = await ctx.broker.call("identity.get", { id: ctx.params.id });
  } catch (err) {
    return new MoleculerError("Error in retrieving user", 500);
  }`

and then inside actions; 

`      async get(ctx) {
        return await userActions.get(ctx);
      },`

This is the only I get it to not crash. If I use Promise.reject in the actual function where I return the Error I get a type error circular to json fault.

**Comment by icebob** [comment]
This code is not correct because it will be a simple response which is `200`. You must throw or reject the errors. The circular JSON error comes from other reason because it should work properly.
