### ISSUE TITLE
Question: service result not retuned to client

### ISSUE THREAD

**Issue by architechcro** [moleculerjs/moleculer-web#61]
Hi,
I may have general usage issue ( due to my ignorace :) ) - so sorry if this question is silly

I have a service action which calls service method which returns a promise ( api call to Twitter )

service action:
```
   user(ctx) {
        console.log('Service TW Request >>>>>>>>>>');
        return this.Promise.resolve()
        .then(() =>{
          return this.user()
            .then( result => {
              this.logger.debug('user method restult', result);
               return result;
            })
            .catch( err => {
              this.logger.error('Twitter user error', err)
              throw new Error(err);
            });
        })

    }
```
method:

```
    user(){
      this.logger.debug('User method called');
      return new Promise((resolve,reject) => {
        client
        .get('account/verify_credentials')
        .then(user => {
          this.logger.debug('user results from twitter');
          resolve(user);
        })
        .catch( error => {
          reject(new MoleculerError(error));
        });
      })
    }
```

Issue is that result returned from the method never reaches client - as if client closes connection before the results.
Maybe there are way to many Promises that I'm not handeling to well - again beacuse of my ignorance.
Any help would be greatly apprechiated.

I have also tried without method, directly calling Twitter rest api ( Twitt library ) but with the same result.
service action usertw :
```
   usertw(ctx) {
      return client
      .get('account/verify_credentials')
      .then(user => {
        this.logger.debug('usertw results from twitter', user);
        return user;
      })
      .catch( error => {
        throw new MoleculerError(error);
      });
    },
```

hope you can help

**Comment by icebob** [comment]
Hi,

please show the caller side too.

**Comment by architechcro** [comment]
when I run moleculer-cli and info I get:
    Node version             : v10.4.0
    Moleculer version        : 0.12.8
but in node_modules I have
  moleculer@0.13.0
  moleculer-web@0.8.0
as read from respective package.json files

**Comment by icebob** [comment]
I have no idea. But if you can make a reproduce repo, I can check it.

**Comment by architechcro** [comment]
Now I see that I didn't mention that I'm using it as Express middleware.
You can see in this repo the issue I mentioned https://github.com/architechcro/emp
When I create Twitter service from Moleuler project template it works ok ->https://github.com/architechcro/apitestproxy .
Difference is that I 'just' use it in Express application.

**Comment by icebob** [comment]
Ohh yes, it's an important information :)
Thanks, I will check it.

**Comment by icebob** [comment]
The reason is a breaking change in 0.8 of API Gateway. In the `onAfterCall` hook, you have to return the `data`. More info: https://github.com/moleculerjs/moleculer-web/blob/master/CHANGELOG.md#the-onaftercall-hook-has-changed
