### ISSUE TITLE
Service with express not working

### ISSUE THREAD

**Issue by davicente** [moleculerjs/moleculer-web#69]
Hi,
I'm trying to create a service with express following the example. But it doesn't work. It's always raising this error:

> ServiceSchemaError: Service name can't be empty! Maybe it is not a valid Service schema.

I only removed the external dependcy with the test service in order to simplify it. 
This is the code. Thanks in advance.

```
"use strict";

let { ServiceBroker } = require("moleculer");

let ApiGatewayService = require("moleculer-web");

let express = require("express");

// Create broker
let broker = new ServiceBroker({
	logger: console
});


// Load API Gateway
const svc = broker.createService({
	mixins: ApiGatewayService,
	name: "myservice",

	settings: {
		middleware: true
	}
});

// Create Express application
const app = express();

// Use ApiGateway as middleware
app.use("/api", svc.express());

// Listening
app.listen(3333, err => {
	if (err)
		return console.error(err);

	console.log("Open http://localhost:3333/api/test/hello");
});

// Start server
broker.start();
```

**Comment by icebob** [comment]
I tried your example and it works, no `ServiceSchemaError`.

**Comment by davicente** [comment]
After several tries, I discovered that launching the service with  ``` node services\myservice.js ```  runs well, but with npm start or npm run dev is when it failes:

```
 "scripts": {
    "dev": "moleculer-runner --repl --hot services",
    "start": "moleculer-runner services"
  },
```

**Comment by icebob** [comment]
I think there is some base problem. If you can start your service file with `node services\myservice.js` it's wrong. A service should be similar as this:
```js
const { MoleculerError } = require("../src/errors");

module.exports = {
	name: "math",
	actions: {
		add(ctx) {
			return Number(ctx.params.a) + Number(ctx.params.b);
		},

		sub(ctx) {
			return Number(ctx.params.a) - Number(ctx.params.b);
		},

		mult: {
			params: {
				a: "number",
				b: "number"
			},
			handler(ctx) {
				return Number(ctx.params.a) * Number(ctx.params.b);
			}
		},

		div: {
			params: {
				a: { type: "number", convert: true },
				b: { type: "number", notEqual: 0, convert: true }
			},
			handler(ctx) {
				let a = Number(ctx.params.a);
				let b = Number(ctx.params.b);
				if (b != 0 && !Number.isNaN(b))
					return a / b;
				else
					throw new MoleculerError("Divide by zero!", 422, null, ctx.params);
			}
		}
	}
};
```

**Comment by icebob** [comment]
Your file is a simple Node app which creates broker, loads a service and starts a broker. But these steps should do Moleculer Runner. I recommend you that create a project with `moleculer init` and modify the `services\api.service.js` to use `express`. [Like this](https://github.com/moleculerjs/moleculer-examples/blob/master/blog/services/www.service.js)

**Comment by davicente** [comment]
The problem with that approach is how I get the service to join it to express framework: 

```
const app = express();
app.use("", svc.express());
```

I'd need svc object from somewhere, and I don't know how to get with your approach.
Do you see my point?

(thanks again for your support)

**Comment by davicente** [comment]
Great. 
That makes sense.
Thanks a lot for your help. 
I close the issue.
