### ISSUE TITLE
Authenticating a Socket using JWT

### ISSUE THREAD

**Issue by jbonnett92** [moleculerjs/moleculer-web#75]
Hi,
Looking at `moleculer-web/examples/socket.io/index.js` how would I implement authentication using the example method:
```/**
 * Authorize the request
 *
 * @param {Context} ctx
 * @param {Object} route
 * @param {IncomingRequest} req
 * @returns {Promise}
 */
authorize(ctx, route, req) {
	let token;
	if (req.headers.authorization) {
		let type = req.headers.authorization.split(" ")[0];
		if (type === "Token" || type === "Bearer")
			token = req.headers.authorization.split(" ")[1];
	}

	return this.Promise.resolve(token)
		.then(token => {
			if (token) {
				// Verify JWT token
				return ctx.call("users.resolveToken", { token })
					.then(user => {
						if (user) {
							this.logger.info("Authenticated via JWT: ", user.username);
							// Reduce user fields (it will be transferred to other nodes)
							ctx.meta.user = _.pick(user, ["_id", "username", "email", "image"]);
							ctx.meta.token = token;
							ctx.meta.userID = user._id;
						}
						return user;
					})
					.catch(err => {
						// Ignored because we continue processing if user is not exist
						return null;
					});
			}
		})
		.then(user => {
			if (req.$action.auth == "required" && !user)
				return this.Promise.reject(new UnAuthorizedError());
		});
},
```

I attempted to do it like so:
```
this.io.use(function (socket, next) {
	let token;

	if (socket.handshake.query.auth_token) {
		socket.request.headers.authorization = `Bearer ${socket.handshake.query.auth_token}`
		
		this.authorize(this.broker, {}, socket.request)
	}

	return next();
}.bind(this));
````
Although I can't seem to get the `req.$action.auth == "required"` part to work in the authorize method, maybe one of you know how to translate a socket request into a Moleculer one?

Thanks,
Jamie

**Comment by jbonnett92** [comment]
I don't think this would work with JWT, in the example you have to emit an event to login (session based). With JWT the token has to be checked on every event meaning the use of middleware and the middleware moleculer-io is the same as `io.use`.

**Comment by tiaod** [comment]
@jbonnett92 If you don't want to emit an event to login:
```javascript
// Using moleculer-io
broker.createService({
  name: 'io',
  mixins: [SocketIOService],
  settings: {
    namespaces: {
      '/': {
        middlewares: [
          async (socket, next) => {
            if (socket.request.headers.authorization) {
              let token
              let type = socket.request.headers.authorization.split(" ")[0];
              if (type === "Token" || type === "Bearer")
                token = socket.request.headers.authorization.split(" ")[1];
              try {
                let user = await ctx.call("users.resolveToken", {
                  token
                })
              } catch (err) {
                return next(new Error('Authentication error'));
              }
              this.logger.info("Authenticated via JWT: ", user.username);
              // Reduce user fields (it will be transferred to other nodes)
              socket.client.user = _.pick(user, ["_id", "username", "email", "image"]);
            }
            next()
          }
        ]
      }
    }
  }
})
```
Then you can check if a user is login:
```javascript
broker.createService({
  name: 'accounts',
  actions: {
    getUserInfo(ctx){
      if(!ctx.meta.$user) throw new Error('Unauthorized')
      return ctx.meta.$user // Return User info
    }
  }
})

**Comment by jbonnett92** [comment]
Thank you @tiaod,
How would you check if a services action has `auth: "required"`? Rather than forcing a socket user to be logged in? This is where `req.$action` comes into play right?

**Comment by jbonnett92** [comment]
@tiaod Sorry I missed that, so there is no way of using `req.$action.auth == "required"` to make it cleaner?

**Comment by jbonnett92** [comment]
@tiaod I noticed that I had a problem with CORS, maybe it could be added to molecular-io? Here is a fix [https://github.com/socketio/socket.io-client/issues/1140](https://github.com/socketio/socket.io-client/issues/1140)

**Comment by tiaod** [comment]
@jbonnett92 Sorry about that. 
According to [socket.io document](https://socket.io/docs/client-api/#With-extraHeaders), Custom headers will not be appended when using websocket as the transport any more. So the example I wrote is wrong.
> With extraHeaders
This only works if polling transport is enabled (which is the default). Custom headers will not be appended when using websocket as the transport. This happens because the WebSocket handshake does not honor custom headers. (For background see the WebSocket protocol RFC)

Here is the example using query to pass JWT token:
```javascript
broker.createService({
  name: 'io',
  mixins: [SocketIOService],
  settings: {
    namespaces: {
      '/': {
        middlewares: [
          async (socket, next) => {
            if (socket.request.headers.authorization) {
              let token = socket.handshake.query.token
              try {
                let user = await ctx.call("users.resolveToken", {
                  token
                })
              } catch (err) {
                return next(new Error('Authentication error'));
              }
              this.logger.info("Authenticated via JWT: ", user.username);
              // Reduce user fields (it will be transferred to other nodes)
              socket.client.user = _.pick(user, ["_id", "username", "email", "image"]);
            }
            next()
          }
        ]
      }
    }
  }
})
```

**Comment by jbonnett92** [comment]
I thought query strings were bad practice from a security point of view?
I also changed the if to `socket.handshake.query.token` although I now get a `Authentication error` when the query string is being passed.

<img width="430" alt="screen shot 2018-08-28 at 15 12 28" src="https://user-images.githubusercontent.com/3740700/44728606-d352ae80-aad4-11e8-9115-e16d1dc52cd3.png">

**Comment by tiaod** [comment]
@jbonnett92 Have you write `users.resolveToken` service to validate your jwt token? You can `console.log(err)` when you catch the error to see what happend.

**Comment by jbonnett92** [comment]
I already have the action:
```
resolveToken: {
	cache: {
		keys: ["token"],
		ttl: 60 * 60 // 1 hour
	},
	params: {
		token: "string"
	},
	handler(ctx) {
		return new this.Promise((resolve, reject) => {
			jwt.verify(ctx.params.token, this.settings.JWT_SECRET, (err, decoded) => {
				if (err)
					return reject(err);

				resolve(decoded);
			});

		})
		.then(decoded => {
			if (decoded.id)
				return this.getById(decoded.id);
		});
	}
},
```
I ready tied logging it but `this.logger.info` just triggers an error `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'info' of undefined`.

**Comment by jbonnett92** [comment]
@tiaod Something looks fishy when calling 'users.resolveToken' `ctx.call` the context doesn't exit. I did try `this.call` but that didn't work either.

**Comment by icebob** [comment]
If you use `async (socket, next) => {` syntax you will lost the `this` binding. It's the reason why you get `Cannot read property 'info ' of undefined` because `this` is not pointed to the service instance.
Use `async function(socket.next) {` form.

**Comment by jbonnett92** [comment]
Ok the way I figured out using this is to bind it replacing [https://github.com/tiaod/moleculer-io/blob/e0569890dea812ae9147e5287a08eb24b44e7540/lib/index.js#L163](this line) to `let middleware = _step.value.bind(this);`, probably not the best way of doing it?

Still in progress of getting the JWT to work, but I'll keep you informed.

**Comment by tiaod** [comment]
@jbonnett92 Good idea! Since moleculer-io v0.11.0, in middlewares the `this` is always pointed to the Service instance.

Btw I'm using babel so you should read `src/` to find the source code.

**Comment by jbonnett92** [comment]
Now time to figure out how to trigger a socket event from another service (possibly from a broadcast) and then figure out how I'm going to handle rooms without it being too inefficient.

Thanks guys for the help :)
