### ISSUE TITLE
httpHandler - improve error logging

### ISSUE THREAD

**Issue by designtesbrot** [moleculerjs/moleculer-web#76]
As if now the httpHandler logs every error:
```javascript
// ...
}).catch(err => {
    this.logger.error("   Request error!", err.name, ":", err.message, "\n", err.stack, "\nData:", err.data);
    this.sendError(req, res, err);
});
```

My suggestion is to change it to:
```javascript
// ...
}).catch(err => {
    if (err.code >= 500) {
        this.logger.error("   Request error!", err.name, ":", err.message, "\n", err.stack, "\nData:", err.data);
    }
    this.sendError(req, res, err);
});
```

Error logging is mostly performed in order to monitor Business Process Healthiness. Logging Errors is a good practice, but it should be from my perspective limited to errors that occured server side (5XX Status Code). Let's say a client requested a record that does not exist and an action returns an error with a code of 404. As all 4XX status codes, the response is expected and does not indicate an error on the server but on the client. It's actually an expected response. Having an error logged (including a stack trace) is from my perspective not beneficial, as error logging should be limited to unexpected errors. In this case the client needs attention, not the server. Meaning the client should perform logging in order to raise awareness of such issues.

What do you think?

**Comment by designtesbrot** [comment]
@icebob any thoughts on this?

**Comment by icebob** [comment]
It's a good idea, but need a service setting to enable logging 4xx errors too (in case of backward compatibility). Could you create a PR?
