### ISSUE TITLE
Service exposes passwords via `settings`

### ISSUE THREAD

**Issue by paulsherwinang** [moleculerjs/moleculer-web#78]
Hi,

I am not sure if this should be posted here in this repo, but $node.services endpoint seems to expose each services settings, and in turn, it blindly exposes the moleculer-mail's credentials stored in the mail settings.

![screen](https://user-images.githubusercontent.com/5292042/46450771-a2495600-c7c5-11e8-9b30-8624c294c0f4.png)

Is this issue under the scope of moleculer-mail or moleculer-web?

**Comment by paulsherwinang** [comment]
I am using env variables in my source code as shown below

<img width="424" alt="screenshot 2018-10-04 at 11 15 11 am" src="https://user-images.githubusercontent.com/5292042/46451010-e1c47200-c7c6-11e8-9eec-bb65438292c7.png">

**Comment by AndreMaz** [comment]
You must be [Whitelisting](http://moleculer.services/docs/0.13/moleculer-web.html#Whitelist) with "**" which gives access to every node, including the `$node`

Consider creating something like 

```js
broker.createService({
    mixins: [ApiService],

    settings: {
        routes: [
            // Only for Admins
            {
                path: "/admin",
                 
                // Always use authorization. 
                // More info here: http://moleculer.services/docs/0.13/moleculer-web.html#Authorization
                authorization: true,

                whitelist: [
                    "$node.*",
                    "users.*",
                ]
            },
            // For public usage
            {
                path: "/",

                whitelist: [
                    "posts.*",
                    "math.*",
                ]
            }
        ]
    }
});
```

**Comment by icebob** [comment]
The `$secureSettings` came with v0.13.6: https://github.com/moleculerjs/moleculer/blob/master/CHANGELOG.md#secure-service-settings
