### ISSUE TITLE
moleculer web explorer

### ISSUE THREAD

**Issue by paulsherwinang** [moleculerjs/moleculer-web#81]
Hi guys,

In my company, we are strongly considering using Moleculer as its a great framework for microservices. We used to come from Loopback and one of the most useful things they have is the component explorer (https://www.npmjs.com/package/loopback-component-explorer). This uses swagger built in for Loopback

Would there be any alternatives for Moleculer web and its services apis?

Any tips and leads would be greatly appreciated!

**Comment by icebob** [comment]
Hi @paulsherwinang,

it's a great news! Currently there is no swagger/openapi module for Moleculer API Gateway. I plan to create one in the future, but I have no enough time at present. 
By the way, I plan to create a swagger mixin for API Gateway which collects the `docs` properties from action definition and generate the swagger specs from them like fastify-swagger module.

```js
module.exports = {
    name: "posts",
    actions: {
        list: {
            docs: {
                description: "Returns all posts that the logged in user has access to",
                responses: {
                    "200": {
                        description: "List of posts",
                        content: {
                            "application/json": {
                                schema: {...}
                            }
                        }
                    }
                }
            }
            handler(ctx) {...}
        }
    }
}
```

**Comment by icebob** [comment]
OpenAPI 3 mixin for moleculer-web is coming in a separated repo

**Comment by jamesbirrellgray** [comment]
@icebob where can I follow the the OpenAPI mixin for molecular-web please?

**Comment by icebob** [comment]
It's in progress. [Here is a WIP](https://github.com/icebob/kantab/blob/master/backend/mixins/openapi.mixin.js)

**Comment by intech** [comment]
I tried on one of the projects. Very uncomfortable. Description openapi is more business application logic.
I see a less flexible tool for autogenerating documentation. It should take the most information from the written code and be accompanied only by comments.

**Comment by icebob** [comment]
I see, I'm thinking on to generate schema from validation schema but somehow need to define responses & components too. I'm open to suggestions.

**Comment by gintsgints** [comment]
Another approach would be generating moleculerjs services based on Swagger

**Comment by HighSoftWare96** [comment]
Any news on this?
