### ISSUE TITLE
How to get original IP address of API client?

### ISSUE THREAD

**Issue by yuricodes** [moleculerjs/moleculer-web#82]
I'm trying to get client IP address from request.

```js
const clientIp = req.headers['x-forwarded-for'] || req.connection.remoteAddress || req.socket.remoteAddress || req.connection.socket.remoteAddress
```

This returns 127.0.0.1. I've tried using TCP, NATS and Redis transporters on my production server. This returns IP of node every time.

How do I configure moleculer to send original client IP with request headers as 'x-forwarded-for'?

**Comment by icebob** [comment]
Use `onBeforeCall` hook and save it to `ctx.meta`.
E.g.:
```js
onBeforeCall(ctx, route, req, res) {
	ctx.meta.clientIp = req.headers['x-forwarded-for'] || req.connection.remoteAddress || req.socket.remoteAddress || req.connection.socket.remoteAddress;
}
```

**Comment by yuricodes** [comment]
@icebob Thanks. I've tried to move this line into `onBeforeCall` hook. But it's still returns `127.0.0.1` instead of client ip.

**Comment by yuricodes** [comment]
Actually this works. Sorry. I've forgot about NGINX proxy in production environment.
