### ISSUE TITLE
Please help me to find Travis issue

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer-web#89]
Hi guys,
Somebody can help me to find why Jest doesn't exited after tests, but only on Travis. In local it works properly.
This problem started 3 months ago after https://github.com/moleculerjs/moleculer-web/commit/ef4385cf76e644bf2bac1699a4761472e1341b10
Travis build history: https://travis-ci.org/moleculerjs/moleculer-web/builds

Error message:
```
Ran all test suites.
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

I've checked open handles but [nothing](https://travis-ci.org/moleculerjs/moleculer-web/jobs/438323914).

Thanks in advance!

**Comment by lucduong** [comment]
@icebob I already checked your commit, `ef4385c` but itsn't correct one. After removing that test case, the error still occurred.

This error happened when some process still running even the last test case completed.
To prevent this, pls add `--detectOpenHandles --forceExit` into `jest --coverage`. 

It should be: 
```bash
jest --coverage --detectOpenHandles --forceExit
```

PS: I still working on this issue. If I found somethings I will create the P/R.

**Comment by icebob** [comment]
Thank @lucduong for your help. I really appreciate it.

I've changed the test script command what you suggest and test ran without timeout: https://travis-ci.org/moleculerjs/moleculer-web/jobs/461668270
So the `--forceExit` solved the issue, but there is no any information about why it is not working without this parameter.

**Comment by lucduong** [comment]
@icebob I read all the Unit Tests in your integration test file. Anyway, I couldn't know which process still running after finishing all the tests.
There is only one information that light me is some processes still running.
`--forceExit` to stop those one.

**Comment by icebob** [comment]
Thanks. If I can reproduce it in local I will start to comment out all tests and give back one-by-one and check the result. But it will be too slow via Travis.
