### ISSUE TITLE
Using regex in alias

### ISSUE THREAD

**Issue by dalmatele** [moleculerjs/moleculer-web#95]
Hi,
I tried to use regex in alias.
Expected:
I want our service will route all /api/* get to method api.gateway.doGet
But in the fact that moleculer web only route /api/* to  this method, not /api/getEntity.
Does moleculer support this case? If not, do you have plan for this function?

**Comment by icebob** [comment]
API Gateway uses [path-to-regexp](https://github.com/pillarjs/path-to-regexp). 
So use this form in aliases: https://github.com/pillarjs/path-to-regexp#zero-or-more

**Comment by dalmatele** [comment]
I've used moleculer-web.
With Express Nodejs, I can do this:
`app.get("/api/*", async (req, res) => {
  let originUrl = "http://localhost:3000" + req.originalUrl;
  let options = {
    method: "GET",
    url: originUrl
  };
  let resp = await new Promise((resolve, reject) => {
    utilities.request(options, originUrl, (err, result) => {
      if (err) {
        return reject(err);
      } else {
        return resolve(result);
      }
    });
  });
  res.send(resp);
});`

**Comment by icebob** [comment]
Please create a reproduction service.

**Comment by wyrd-code** [comment]
For anyone looking for something akin to "/api/*", you can use regexp to achieve this:

```
        aliases: {
          "GET /api/(.*)": "your-service.method",
        },
```

@icebob I think this would be very useful to note somewhere in the docs.
It took me quite some time to figure it out. Cheers

**Comment by AndreMaz** [comment]
Good idea @wyrd-code can you create a PR?
