### ISSUE TITLE
Static assets don't work when exists route with empty path

### ISSUE THREAD

**Issue by dbshell** [moleculerjs/moleculer-web#99]
I have isolated from my project following code, which causes problems. The problem is that when route settings contains path, everything is OK, but when path is empty or path is missing, moleculer web returns error ServiceNotFoundError - probably request is handled by service resolving code, not by static assets middleware.

In following code (saved as test.js), GET http://localhost:3000/test.js fails. When uncommenting line  `path: "/api",`, everything is OK.
Used Package versions:
    "moleculer": "0.13.5",
    "moleculer-web": "0.8.5"

```javascript
const { ServiceBroker } = require("moleculer");
let ApiService = require("moleculer-web");

// Create a broker
let broker = new ServiceBroker({ logger: console });

// Create a service
broker.createService({
name: "test",
actions: {
    hello() {
    return "Hello API Gateway!";
    }
}
});

// Load API Gateway
broker.createService({
name: "api",
mixins: [ApiService],
settings: {
    routes: [
    {
        // path: "/api",
        // path: "",
        whitelist: "test.hello"
    }
    ],

    assets: {
    // Root folder of assets
    folder: __dirname,

    // Options to `server-static` module
    options: {}
    }
}
});

// Start server
broker.start();
```

**Comment by icebob** [comment]
Yes it's true. API gateway doesn't support to use static files & service calls on the same path. Workaround if you don't use the internal static handler, instead use `serve-static` middleware inside the route.

**Comment by dbshell** [comment]
Thank you, with serve-static middleware it works perfectly
